import { AST, SpeckNode, MemberNode, StateNode, InitNode, ActionNode, ConstraintNode, EventNode } from '../parser.js';
import fs from 'fs';
import path from 'path';

/**
 * Generate Go from a SpeckDL spec.
 *
 * Outputs a self-contained Go package with:
 *  - State struct + machine with action methods returning (ret, err)
 *  - Guards (require) become errors; emits append to an event log
 *  - Invariant check methods (read-only)
 *  - Event structs
 *  - handlers.go: HTTP + htmx surface, one POST endpoint per action
 *  - go.mod
 *
 * Clean-room: generated from the SpeckDL specification only.
 */

export function generateGo(ast: AST, outputDir: string): void {
  for (const speck of ast.specks) {
    const pkg = snakeCase(speck.name);
    const speckDir = path.join(outputDir, pkg);
    fs.mkdirSync(speckDir, { recursive: true });

    fs.writeFileSync(path.join(speckDir, 'go.mod'), `module speckl/${pkg}\n\ngo 1.22\n`);
    fs.writeFileSync(path.join(speckDir, `${pkg}.go`), emitSpeck(speck));
    fs.writeFileSync(path.join(speckDir, 'handlers.go'), emitHandlers(speck));
    fs.writeFileSync(path.join(speckDir, 'prelude.go'), preludeFile.replace('package __prelude', `package ${pkg}`));
    fs.writeFileSync(path.join(speckDir, 'store.go'), emitStore(speck));
    const cmdDir = path.join(speckDir, 'cmd', 'server');
    fs.mkdirSync(cmdDir, { recursive: true });
    fs.writeFileSync(path.join(cmdDir, 'main.go'), emitMain(speck));
    fs.writeFileSync(path.join(speckDir, 'Dockerfile'), emitDockerfile(speck));
    console.log(`Generated Go package: ${speckDir} (machine + handlers + prelude + store + main + Dockerfile)`);
  }
}

// ─── types ──────────────────────────────────────────────────────────

const preludeFile = `// Code generated by speckl: generic helpers for spec collection expressions.
// These back the collection syntax used by SpeckDL specs (has, in, count).
package __prelude

import (
	"strconv"
	"strings"
	"time"
)

func mapHas[M ~map[K]V, K comparable, V any](m M, k K) bool { _, ok := m[k]; return ok }
func inSet[K comparable](k K, set map[K]bool) bool { return set[k] }
func setContains[T comparable](set map[T]bool, k T) bool { return set[k] }
func inValues[K comparable, V any](m map[K]V, v V) bool {
	for _, x := range m {
		if any(x) == any(v) {
			return true
		}
	}
	return false
}
func countWhere[V any](coll []V, pred func(V) bool) int {
	n := 0
	for _, x := range coll {
		if pred(x) {
			n++
		}
	}
	return n
}
func nowString() string { return strconv.FormatInt(time.Now().Unix(), 10) }
func listContains[T comparable](xs []T, v T) bool {
	for _, x := range xs {
		if any(x) == any(v) {
			return true
		}
	}
	return false
}
func slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b []rune
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b = append(b, r)
		} else if len(b) > 0 && b[len(b)-1] != '-' {
			b = append(b, '-')
		}
	}
	return strings.Trim(string(b), "-")
}
func toInt(v any) int64 {
	switch x := v.(type) {
	case string:
		n, _ := strconv.ParseInt(x, 10, 64)
		return n
	case *string:
		if x == nil { return 0 }
		n, _ := strconv.ParseInt(*x, 10, 64)
		return n
	case int64:
		return x
	}
	return 0
}
`;

function goType(t: any, speckName: string, enumMap: Map<string, string[]>): string {
  if (!t) return 'any';
  if ((t.type as any) === 'union' || Array.isArray(t)) {
    // T | null -> *T
    const members: any[] = t.types ?? t;
    const nonNull = members.find((x: any) => !(x.name === 'null' && x.type !== 'ident') && !(x.type === 'ident' && x.name === 'null'));
    if (nonNull) return '*' + goType(nonNull, speckName, enumMap);
    return 'any';
  }
  if (t.type === 'primitive') {
    const map: Record<string, string> = {
      Nat: 'int64', Int: 'int64', Real: 'float64', Number: 'float64',
      Bool: 'bool', String: 'string', Bytes: '[]byte', Date: 'int64',
    };
    const base = map[t.name] || t.name.toLowerCase();
    return (t as any).nullable ? '*' + base : base;
  }
  if (t.type === 'list') return `[]${goType(t.elementType, speckName, enumMap)}`;
  if (t.type === 'set') return `map[${goType(t.elementType, speckName, enumMap)}]bool`;
  if (t.type === 'map') return `map[${goType(t.keyType, speckName, enumMap)}]${goType(t.valueType, speckName, enumMap)}`;
  if (t.type === 'record') {
    const fields = t.fields.map((f: any) => `${goName(f.name)} ${goType(f.type, speckName, enumMap)}`).join('; ');
    return `struct { ${fields} }`;
  }
  if (t.type === 'ident') {
    const raw = cleanName(t.name);
    if (enumMap?.has(raw)) return `${goName(speckName)}${goName(raw)}`;
    const prim: Record<string, string> = { Nat: 'int64', Int: 'int64', Bool: 'bool', String: 'string', Date: 'int64', Real: 'float64', Number: 'float64' };
    if (prim[raw]) return t.nullable ? '*' + prim[raw] : prim[raw];
    const opt = raw.match(/^Option[_(]\s*(\w+)\s*\)?$/);
    if (opt) return '*' + (prim[opt[1]] || goName(opt[1]));
    return t.nullable ? '*' + goName(raw) : goName(raw);
  }
  return 'any';
}

// ─── expression rewriting ───────────────────────────────────────────

function rewriteGoExpr(
  expr: string,
  nameMap: Map<string, string>,
  mapVarOrigNames: Set<string>,
  localNames: Set<string>,
  stateEnumName: string,
  knownStateValues: string[]
): string {
  const shouldPrefix = (ident: string) => nameMap.has(ident) && !localNames.has(ident);
  const goify = (ident: string) => nameMap.has(ident) && !localNames.has(ident) ? `m.${nameMap.get(ident)}` : ident;

  let g = expr
    .replace(/Date\.now\(\)\.toString\(\)/g, 'nowString()')
    .replace(/Date\.now\(\)/g, 'time.Now().Unix()')
    .replace(/\bnow\(\)/g, 'time.Now().Unix()')
    .replace(/\btoInt\(([^)]+)\)/g, 'toInt($1)')
    .replace(/\blength\(([^)]+)\)/g, 'len($1)')
    .replace(/\blen\(([^)]+)\)/g, 'len($1)')
    .replace(/\bjoin\(([^,]+),\s*([^)]+)\)/g, 'strings.Join($1, $2)')
    .replace(/\bappend\(([^,]+),\s*([^)]+)\)/g, 'append($1, $2)')
    .replace(/(\w+)\.has\(([^)]+)\)/g, 'mapHas($1, $2)')
    .replace(/([\w.]+)\.contains\(([^)]+)\)/g, 'listContains($1, $2)')
    .replace(/\bcount\(([^,]+),\s*(\w+)\s*=>\s*([^)]+)\)/g, 'countWhere($1, func($2 any) bool { return $3 })');

  // state enum literals -> typed consts (skip field accesses `x.passed`,
  // record-literal keys `registered:`, and quoted strings)
  for (const [val, constName] of enumValueConsts) {
    g = g.replace(new RegExp('(?<![.\\w])' + escapeRegex(val) + '(?![\\w":])', 'g'), constName);
  }

  // identifier prefixing
  g = g.split(/([\s()\[\]{}+\-*/=<>!&|.,;:'"`]+)/).map(tok => {
    if (/^(true|false|nil|null|not|and|or|in|notIn|old|forall|let|if|else|time|fmt|strings)$/.test(tok)) return tok;
    if (/^\d+(\.\d+)?$/.test(tok)) return tok;
    if (/^[a-zA-Z_]\w*$/.test(tok) && shouldPrefix(tok)) return goify(tok);
    return tok;
  }).join('');
  g = g.replace(/\]\.m\.(\w+)/g, '].$1');

  // speckdl patterns -> go
  g = g
    .replace(/(\w+)\s+notIn\s+(\w+)\.keys/g, '!mapHas($2, $1)')
    .replace(/(\w+)\s+in\s+(\w+)\.keys/g, 'mapHas($2, $1)')
    .replace(/(\w+)\s+notIn\s+(\w+)\.values/g, '!inValues($2, $1)')
    .replace(/(\w+)\s+in\s+(\w+)\.values/g, 'inValues($2, $1)')
    .replace(/\bnot\s*\(/g, '!(')
    .replace(/old\(([^()]*(?:\([^()]*\)[^()]*)*)\)/g, '$1')
    .replace(/\.size\(\)/g, '.len')
    .replace(/\b===\b/g, '==')
    .replace(/\bnull\b/g, 'nil');

  // bare map var bracket access -> m.field[k]
  for (const mapVar of mapVarOrigNames) {
    const gname = nameMap.get(mapVar) || camelCase(mapVar);
    const bare = new RegExp(`(?<![\\w.])${escapeRegex(mapVar)}\\[`, 'g');
    g = g.replace(bare, `m.${gname}[`);
  }

  // set membership: target in { "a", "b", "c" } -> (target == "a" || target == "b" || target == "c")
  g = g.replace(/([\w.]+)\s+in\s+\{([^}]+)\}/g, (_, ident, values) => {
    const vals = values.split(',').map((v: string) => v.trim().replace(/"/g, ''));
    return '(' + vals.map((v: string) => `${ident} == ${JSON.stringify(v)}`).join(' || ') + ')';
  });

  // array membership: target in [ "a", "b" ] -> (target == "a" || target == "b")
  g = g.replace(/([\w.]+)\s+in\s+\[([^\]]+)\]/g, (_, ident, values) => {
    const vals = values.split(',').map((v: string) => v.trim());
    return '(' + vals.map((v: string) => `${ident} == ${v}`).join(' || ') + ')';
  });

  // implies -> !(p) || (q)
  let changed = true;
  while (changed) {
    changed = false;
    g = g.replace(/implies\s*\(([^,()]*(?:\([^()]*\)[^()]*)*),\s*([^()]*(?:\([^()]*\)[^()]*)*)\)/g, (_, p, q) => {
      changed = true;
      return `(!(${p.trim()}) || (${q.trim()}))`;
    });
  }
  g = g.replace(/\bnot\s+([a-zA-Z_]\w*)/g, '!$1');
  // forall cannot be an expression in Go; lower at the invariant-statement level.
  // Any residual forall is surfaced as a visible TODO, never silently dropped.
  if (/forall/.test(g)) g = `/* UNLOWERED forall - manual attention required */ (${g})`;
  // record field casing: .column -> .Column (known record fields)
  for (const [lower, G] of goFieldRenames) {
    g = g.replace(new RegExp(`\\.${lower}\\b`, 'g'), `.${G}`);
  }
  // record literal field casing: Project { projectId: v } -> Project { ProjectId: v }
  for (const [typeName, fields] of recordTypes) {
    const fieldKeys = fields.map(f => escapeRegex(f)).join('|');
    const re = new RegExp(`\\b${typeName}\\s*\\{([^{}]*)\\}`, 'g');
    g = g.replace(re, (m2, inner) => `${typeName}{ ` +
      inner.replace(new RegExp(`\\b(${fieldKeys})\\s*:`, 'g'), (_m: string, f: string) => `${goName(f)}:`) + ' }');
  }
  return g.trim();
}

function goImplications(expr: string): string {
  let e = expr; let changed = true;
  while (changed) {
    changed = false;
    e = e.replace(/implies\s*\(([^,()]*(?:\([^()]*\)[^()]*)*),\s*([^()]*(?:\([^()]*\)[^()]*)*)\)/g, (_, p, q) => {
      changed = true;
      return `(!(${p.trim()}) || (${q.trim()}))`;
    });
  }
  // infix implies: A implies B -> (!(A) || (B))  (split at paren depth 0, recursive)
  const lowerInfixImplies = (s: string): string => {
    let depth = 0;
    for (let i = 0; i < s.length; i++) {
      const ch = s[i];
      if (ch === '(') depth++;
      else if (ch === ')') depth--;
      else if (depth === 0 && s.startsWith('implies', i)
        && (i === 0 || /\s/.test(s[i - 1]))
        && (s[i + 7] === undefined || /\s/.test(s[i + 7]))) {
        const left = lowerInfixImplies(s.slice(0, i).trim());
        const right = lowerInfixImplies(s.slice(i + 7).trim());
        return `(!(${left}) || (${right}))`;
      }
    }
    return s;
  };
  e = lowerInfixImplies(e);
  e = e.replace(/\bnot\s+([a-zA-Z_]\w*)/g, '!$1');
  e = e.replace(/\bor\b/g, '||').replace(/\band\b/g, '&&');
  return e;
}

// ─── speck emission ─────────────────────────────────────────────────

let goFieldRenames: Map<string, string> = new Map();
let enumValueConsts: Map<string, string> = new Map();
let recordFieldTypes: Map<string, Map<string, any> = new Map();
let currentEnumMap: Map<string, string[]> = new Map();
let stateVarTypes: Map<string, any> = new Map();
let recordTypes: Map<string, string[]> = new Map();
function stateVarsOf(name: string): string {
  const t = stateVarTypes.get(name);
  if (t && t.type === 'list') return goType(t.elementType, 'Spot', new Map());
  return 'any';
}
function fixRecordLiteral(expr: string, elemType: string): string {
  // uppercase record literal fields: CardEvent { cardId: x } -> CardEvent{ CardId: x }
  const m = expr.match(/^(\w+)\s*\{([\s\S]*)\}$/);
  if (!m) return expr;
  const inner = m[2].replace(/(\w+)\s*:/g, (_, f) => `${goName(f)}:`);
  return `${m[1]}{ ${inner} }`;
}

function emitSpeck(speck: SpeckNode): string {
  stateVarTypes = new Map();
  for (const m of speck.members) {
    if (m.type === 'state') for (const v of (m as any).variables) stateVarTypes.set((v as any).name, v.typeExpr);
  }
  const deduped = new Map<string, MemberNode>();
  for (const m of speck.members) {
    const key = memberKey(m);
    const existing = deduped.get(key);
    if (!existing || isEmptyStub(existing)) deduped.set(key, m);
  }
  const members = Array.from(deduped.values());

  // Merge all state members (multiple entities per speck)
  const stateNodes = members.filter(m => m.type === 'state') as StateNode[];
  let mergedState: any = undefined;
  if (stateNodes.length > 0) {
    mergedState = { type: 'state', variables: stateNodes.flatMap(function(n) { return n.variables; }) } as any;
  }
  const stateNode: any = mergedState;
  const initNodes = members.filter(m => m.type === 'init') as any[];  const initNode: any = initNodes.length > 0 ? {
    type: 'init',
    assignments: initNodes.flatMap(function(n) { return n.assignments; }),
  } : undefined;
  const actions = members.filter(m => m.type === 'action') as ActionNode[];
  const events = members.filter(m => m.type === 'event') as EventNode[];
  const constraints = members.filter(m => m.type === 'constraint') as ConstraintNode[];
  const allInterfaces = members.filter(m => m.type === 'interface') as any[];

  const enumMap = new Map<string, string[]>();
  for (const iface of allInterfaces) {
    if (iface?.methods?.length > 0) enumMap.set(iface.name, iface.methods.map((m: any) => m.name));
  }
  currentEnumMap = enumMap;

  const goNameS = goName(speck.name);
  const speckName = speck.name;
  const structName = `${goNameS}Machine`;

  // state enum
  const stateVarType = stateNode?.variables?.[0]?.typeExpr;
  let stateEnumName = `${goNameS}State`;
  if (stateVarType?.type === 'ident' && stateVarType.name) {
    stateEnumName = `${goNameS}${goName(cleanName(stateVarType.name))}`;
  } else if (enumMap.size > 0) {
    const first = enumMap.keys().next().value;
    if (first) stateEnumName = `${goNameS}${goName(first)}`;
  }

  const stateVars: { origName: string; goName: string; typeExpr: any }[] =
    ((stateNode?.variables ?? []) as any[]).map((v: any) => ({
    origName: cleanName(v.name),
    goName: goName(cleanName(v.name)),   // exported so JSON snapshot persistence works
    typeExpr: v.typeExpr,
  }));
  const nameMap = new Map<string, string>();
  for (const v of stateVars) nameMap.set(v.origName, v.goName);
  const stateVarOrigNames = new Set(stateVars.map(v => v.origName));
  const mapVarOrigNames = new Set(stateVars
    .filter(v => v.typeExpr?.type === 'map' || (v.typeExpr?.type === 'ident' && v.typeExpr?.name && /^Map/i.test(v.typeExpr.name)))
    .map(v => v.origName));

  // collect record field renames + record literal casing tables (BEFORE rewrites)
  goFieldRenames = new Map();
  recordTypes = new Map();
  for (const m of members) {
    if (m.type === 'interface' && (m as any).fields) {
      recordTypes.set(goName(m.name), (m as any).fields.map((f: any) => f.name));
      recordFieldTypes.set(cleanName(m.name), new Map((m as any).fields.map((f: any) => [f.name, f.type])));
      for (const f of (m as any).fields) goFieldRenames.set(f.name, goName(f.name));
    }
    if ((m.type as any) === 'type' && (m as any).typeExpr?.type === 'record') {
      const fields = (m as any).typeExpr.fields.map((f: any) => f.name);
      recordTypes.set(goName((m as any).name), fields);
      recordFieldTypes.set(cleanName((m as any).name), new Map((m as any).typeExpr.fields.map((f: any) => [f.name, f.type])));
      for (const f of fields) goFieldRenames.set(f.name, goName(f.name));
    }
  }

  // collect known state values (enum interfaces + string literals compared/emitted)
  const known = new Set<string>();
  for (const vals of enumMap.values()) for (const v of vals) known.add(v);
  for (const a of actions) {
    for (const st of a.statements) {
      const ex = String((st as any).expr ?? '');
      for (const m of ex.match(/==\s*"(\w+)"/g) ?? []) known.add(m.split('==')[1].trim().replace(/"/g, ''));
      if (st.type === 'emit') for (const f of (st as any).fields ?? []) {
        for (const m of String(f.value).match(/"([A-Za-z]+)"/g) ?? []) known.add(m.replace(/"/g, ''));
      }
    }
  }
  const knownStateValues = Array.from(known);

  // enum defs
  const enumDefs: string[] = [];
  const seenEnumTypes = new Map<string, string[]>();
  if (knownStateValues.length > 0) seenEnumTypes.set(stateEnumName, knownStateValues);
  for (const [k, v] of enumMap) seenEnumTypes.set(`${goNameS}${goName(k)}`, v);
  for (const [typeName, values] of seenEnumTypes) {
    enumDefs.push(`type ${typeName} string\n`);
    for (const v of Array.from(new Set(values))) {
      enumDefs.push(`const ${typeName}${goName(v)} ${typeName} = ${JSON.stringify(v)}`);
    }
    enumDefs.push('');
  }

  // value -> typed const name, for lowering bare enum literals in expressions
  enumValueConsts = new Map();
  for (const [typeName, values] of seenEnumTypes) {
    for (const v of values) if (!enumValueConsts.has(v)) enumValueConsts.set(v, `${typeName}${goName(v)}`);
  }

  const recordStructs = allInterfaces
    .filter(iface => iface?.kind === 'record' || (iface?.fields && iface.fields.length > 0))
    .map(iface => {
      const fields = iface.fields.map((f: any) => `${goName(f.name)} ${goType(f.type, speck.name, enumMap)}`).join('; ');
      return `type ${goName(iface.name)} struct { ${fields} }`;
    }).join('\n\n');

  const eventStructs = events.map(e => {
    const fields = e.fields.map(f => `${goName(f.name)} ${goType(f.type, speckName, enumMap)}`).join('; ');
    return `type ${goName(e.name)} struct { ${fields} }`;
  }).join('\n\n');

  const stateFields = stateVars.map(v => `${v.goName} ${goType(v.typeExpr, speckName, enumMap)}`).join('\n\t');

    // init: concrete empties for ALL state vars first (nil maps panic on
  // assignment), then apply explicit init assignments as overrides.
  const defaults = stateVars
    .map(v => `\tm.${v.goName} = ${defaultGoValue(v.typeExpr)}`)
    .join('\n');
  const overrides = ((initNode?.assignments ?? []) as any[])
    .filter((a: any) => !/^\w*\.(empty|now)/.test(cleanExpr(a.expr)))
    .map((a: any) => {
      const gname = nameMap.get(cleanName(a.name)) || camelCase(cleanName(a.name));
      const expr = rewriteGoExpr(cleanExpr(a.expr), nameMap, mapVarOrigNames, new Set<string>(), stateEnumName, knownStateValues);
      return `\tm.${gname} = ${expr}`;
    }).join('\n');
  const initBody = overrides ? defaults + '\n' + overrides : defaults;

  const actionMethods = actions
    .map(a => emitAction(a, nameMap, mapVarOrigNames, goNameS, stateEnumName, knownStateValues, enumMap))
    .join('\n\n');

  const invariantChecks = constraints.map((c, i) => {
    const cExpr = c.expr.trim();
    const fname = `Check${goName(c.name || 'Invariant' + i)}`;
    // peel forall prefixes (supports nested forall: forall a ...: forall b ...: body)
    const forallRe = /^forall\s+(\w+)\s+in\s+(\w+)(\.values\(\))?:\s*([\s\S]+)$/;
    const loops: { varName: string; collName: string }[] = [];
    let rest = cExpr;
    let fm: RegExpMatchArray | null;
    while ((fm = rest.match(forallRe))) {
      loops.push({ varName: fm[1], collName: fm[2] });
      rest = fm[4];
    }
    let body: string;
    if (loops.length > 0) {
      const innerExpr = goImplications(rewriteGoExpr(rest, nameMap, mapVarOrigNames, new Set<string>(loops.map(l => l.varName)), stateEnumName, knownStateValues));
      let inner = innerExpr.replace(/\b(\w+)\.(\w+)/g, (m2, obj, f) => {
        const mapped = goFieldRenames.get(f);
        return mapped ? `${obj}.${mapped}` : m2;
      });
      for (const l of loops) inner = inner.replace(new RegExp(`\\b${l.varName}\\b`, 'g'), l.varName + 'Val');
      const lines: string[] = [];
      for (let d = 0; d < loops.length; d++) {
        const gColl = nameMap.get(loops[d].collName) || camelCase(loops[d].collName);
        lines.push(`${'\t'.repeat(d + 1)}for _, ${loops[d].varName}Val := range m.${gColl} {`);
      }
      lines.push(`${'\t'.repeat(loops.length + 1)}if !(${inner}) {`);
      lines.push(`${'\t'.repeat(loops.length + 2)}return false`);
      lines.push(`${'\t'.repeat(loops.length + 1)}}`);
      for (let d = loops.length - 1; d >= 0; d--) lines.push(`${'\t'.repeat(d + 1)}}`);
      lines.push('\treturn true');
      body = lines.join('\n');
    } else {
      body = `\treturn ${goImplications(rewriteGoExpr(cExpr, nameMap, mapVarOrigNames, new Set<string>(), stateEnumName, knownStateValues))}`;
    }
    return `// Invariant ${fname}: ${cExpr.replace(/\s+/g, ' ').slice(0, 90)}\nfunc (m *${structName}) ${fname}() bool {\n${body}\n}`;
  }).join('\n\n');

  // unknown domain functions -> explicit stubs
  const unknown = new Set<string>();
  const unknownBool = new Set<string>();
  const builtin = new Set(['now', 'len', 'length', 'join', 'append', 'mapHas', 'setContains', 'inValues', 'countWhere', 'implies', 'slugify', 'contains', 'has', 'values', 'keys', 'empty', 'size', 'count']);
  const scanCalls = (ex: string, boolCtx: boolean) => {
    for (const m of ex.match(/\b([a-z_]\w*)\s*\(/g) ?? []) {
      const fn = m.replace(/\s*\($/, '');
      if (!builtin.has(fn)) {
        unknown.add(fn);
        if (boolCtx) unknownBool.add(fn);
      }
    }
  };
  for (const a of actions) {
    for (const st of a.statements) {
      const isGuard = st.type === 'require' || st.type === 'precondition';
      scanCalls(String((st as any).expr ?? ''), isGuard);
      if (st.type === 'emit') for (const f of (st as any).fields ?? []) {
        scanCalls(String(f.value), false);
      }
    }
  }
  for (const c of constraints) scanCalls(String((c as any).expr ?? ''), true);
  const stubs = unknown.size > 0
    ? Array.from(unknown).sort().map(fn => {
        const ret = unknownBool.has(fn) ? 'bool' : 'any';
        return `// ${fn} - domain function from the SpeckDL spec. Implement per spec semantics.\nfunc ${fn}(args ...any) ${ret} {\n\tpanic("speckl: domain function not implemented: ${fn}")\n}`;
      }).join('\n\n')
    : '';

  const eventLogField = events.length > 0 ? '\n\t// EventLog records every decision (spec events).\n\tEventLog []any' : '';
  const eventStructsBlock = events.length > 0
    ? eventStructs + `\n\n// ${goNameS}Event union marker.\ntype ${goNameS}Event interface{ is${goNameS}Event() }`
    : '';

  const bodyText = [actionMethods, invariantChecks, initBody].join('\n');
  const importNames = ['fmt', 'strings', 'strconv'].filter(i => bodyText.includes(i + '.'));
  if (bodyText.includes('time.')) importNames.push('time');
  const importBlock = importNames.length > 0
    ? 'import (\n' + importNames.map(i => '\t"' + i + '"').join('\n') + '\n)'
    : '';

  return [
    `// Code generated by speckl (go backend) from ${speck.name}.speckdl. DO NOT EDIT BY HAND.`,
    `// Clean-room generated from the SpeckDL specification; contains no third-party code.`,
    `// Domain-function stubs must be implemented per the spec text.`,
    `package ${snakeCase(speck.name)}`,
    '',
    importBlock,
    '',
    enumDefs.join('\n'),
    '',
    recordStructs,
    '',
    eventStructsBlock,
    '',
    `// ${structName} - state machine generated from the SpeckDL specification.`,
    `type ${structName} struct {`,
    `\t${stateFields}${eventLogField}`,
    '}',
    '',
    `// New${goNameS}Machine constructs the machine in its initial state.`,
    `func New${goNameS}Machine() *${structName} {`,
    `\tm := &${structName}{}`,
    initBody.split('\n').map(l => '\t' + l.trim()).join('\n'),
    `\treturn m`,
    '}',
    '',
    actionMethods,
    '',
    invariantChecks,
    ...(stubs ? ['', stubs] : []),
  ].join('\n');
}

// ─── actions ────────────────────────────────────────────────────────

function emitAction(
  action: ActionNode,
  nameMap: Map<string, string>,
  mapVarOrigNames: Set<string>,
  speckName: string,
  stateEnumName: string,
  knownStateValues: string[],
  enumMap: Map<string, string[]>
): string {
  const localNames = new Set(action.params.map(p => cleanName(p.name)));
  const params = action.params
    .map(p => `${camelCase(cleanName(p.name))} ${goType(p.type, speckName, enumMap)}`)
    .join(', ');
  const methodName = goName(action.name);
  const hasReturn = action.statements.some(s => s.type === 'return');
  const retSig = hasReturn ? '(ret any, err error)' : '(err error)';

  const emitAssign = (s: any): string => {
    const target = String(s.target);
    // nested field assign: mapVar[key].field := val
    const nested = target.match(/^(\w+)\[(.+)\]\.(\w+)$/);
    if (nested) {
      const gname = nameMap.get(cleanName(nested[1])) || camelCase(cleanName(nested[1]));
      const key = rewriteGoExpr(nested[2], nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      const gfield = goFieldRenames.get(nested[3]) || goName(nested[3]);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      // Go: cannot assign through a map to a struct field — read-modify-write
      return [
        `\t{`,
        `\t\tc := m.${gname}[${key}]`,
        `\t\tc.${gfield} = ${val}`,
        `\t\tm.${gname}[${key}] = c`,
        `\t}`,
      ].join('\n');
    }
    const bracket = target.match(/^(\w+)\[(.+)]$/);
    if (bracket) {
      const gname = nameMap.get(cleanName(bracket[1])) || camelCase(cleanName(bracket[1]));
      const key = rewriteGoExpr(bracket[2], nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      return `\tm.${gname}[${key}] = ${val}`;
    }
    // local record field assign: localVar.field := val (let-bound local, not a state var)
    const dotted = target.match(/^(\w+)\.(\w+)$/);
    if (dotted && !nameMap.has(cleanName(dotted[1])) && localNames.has(cleanName(dotted[1]))) {
      const gfield = goFieldRenames.get(dotted[2]) || goName(dotted[2]);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      let v = val;
      const rec = letRecords.get(cleanName(dotted[1]));
      const ftype = rec ? recordFieldTypes.get(rec)?.get(dotted[2]) : undefined;
      if (ftype?.nullable && /^([A-Za-z_]\w*)$/.test(val) && val !== 'nil') v = `&${val}`;
      return `\t${camelCase(cleanName(dotted[1]))}.${gfield} = ${v}`;
    }
    const gname = nameMap.get(cleanName(target)) || camelCase(cleanName(target));
    const rawExpr = String(s.expr);
    // SpeckDL cons: ELEM :: list  ->  list = append([]Elem{elem}, list)
    const cons = rawExpr.match(/^(.+)\s*::\s*(\w+)$/s);
    if (cons) {
      const listVar = cons[2];
      const gname2 = nameMap.get(cleanName(listVar)) || camelCase(cleanName(listVar));
      const elemType = (stateVarsOf(listVar) || '').replace(/^\[\]/, '');
      const elem = fixRecordLiteral(rewriteGoExpr(cons[1].trim(), nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues), elemType);
      return `\tm.${gname2} = append([]${elemType}{ ${elem} }, m.${gname2}...)`;
    }
    const val = rewriteGoExpr(rawExpr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
    return `\tm.${gname} = ${val}`;
  };

  // emit statements in source order so lets declared before guards/assigns
  // that reference them are emitted in the correct sequence
  const letRecords = new Map<string, string>();
  const bodyLines: string[] = [];
  for (const s of action.statements as any[]) {
    if (s.type === 'require' || s.type === 'precondition') {
      const expr = goImplications(rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues));
      bodyLines.push(`\tif !(${expr}) {\n\t\terr = fmt.Errorf("guard failed: ${String(s.expr).replace(/"/g, "'")}")\n\t\treturn\n\t}`);
    } else if (s.type === 'let') {
      localNames.add(s.name);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
      bodyLines.push(`\t${camelCase(s.name)} := ${val}`);
      // track the record type of the let-bound local (for nullable field assigns)
      const exprRaw = String(s.expr ?? '');
      const bracketM = exprRaw.match(/^(\w+)\[(.+)\]$/s);
      if (bracketM) {
        const vt = stateVarTypes.get(bracketM[1]);
        if (vt?.type === 'map' && vt.valueType?.type === 'ident') letRecords.set(cleanName(s.name), cleanName(vt.valueType.name));
      } else {
        const litM = exprRaw.match(/^([A-Za-z_]\w*)\s*\{/);
        if (litM) letRecords.set(cleanName(s.name), cleanName(litM[1]));
      }
    } else if (s.type === 'assign') {
      bodyLines.push(emitAssign(s));
    } else if (s.type === 'emit') {
      const fields = ((s.fields ?? []) as any[])
        .map((f: any) => `${goName(f.name)}: ${rewriteGoExpr(f.value, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues)}`)
        .join(', ');
      bodyLines.push(`\tm.EventLog = append(m.EventLog, ${goName(s.event)}{ ${fields} })`);
    } else if (s.type === 'return') {
      bodyLines.push(`\tret = ${rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues)}`);
    }
  }
  let body = bodyLines.length ? bodyLines.join('\n') : '\treturn';
  body += '\n\treturn';

  return `// Execute action: ${action.name}\nfunc (m *${goName(speckName)}Machine) ${methodName}(${params}) ${retSig} {\n${body}\n}`;
}

// ─── handlers (HTTP + htmx surface) ─────────────────────────────────

function emitHandlers(speck: SpeckNode): string {
  const actions = speck.members.filter(m => m.type === 'action') as ActionNode[];
  const structName = `${goName(speck.name)}Machine`;
  const handlers = actions.map(a => {
    const route = `/actions/${snakeCase(a.name)}`;
    const typedFields = a.params
      .map(p => `\t\t\t${goName(p.name)} ${goType(p.type, speck.name, currentEnumMap)} \`json:"${camelCase(cleanName(p.name))}"\``)
      .join('\n');
    const argNames = a.params.map(p => `req.${goName(p.name)}`).join(', ');
    const hasRet = a.statements.some(s => s.type === 'return');
    const call = hasRet
      ? `ret, err := m.${goName(a.name)}(${argNames})`
      : `err := m.${goName(a.name)}(${argNames})`;
    const resp = hasRet
      ? `\t\tjson.NewEncoder(w).Encode(map[string]any{"ok": true, "result": ret})`
      : `\t\tjson.NewEncoder(w).Encode(map[string]any{"ok": true})`;
    return `	// ${a.name} — POST ${route} (htmx: hx-post="${route}")
	mux.HandleFunc("POST ${route}", auth(func(w http.ResponseWriter, r *http.Request) {
		var req struct {
${typedFields}
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		${call}
		if err != nil {
			json.NewEncoder(w).Encode(map[string]any{"ok": false, "error": err.Error()})
			return
		}
${resp}
		m.Save()
	}));`;
  }).join('\n\n');

  return `// Code generated by speckl (go backend): HTTP + htmx surface.
//
// Frontend model: Go html/template + htmx. Each spec action gets a POST
// endpoint; htmx forms POST to these endpoints and swap fragments with the
// response. Mount with RegisterHandlers(mux, machine).
//
// Auth: set GB_API_KEY to require X-API-Key on every action call.
// Persistence: set GB_STATE_PATH (default ./state.json) — state snapshots
// are written after every successful mutation and loaded at boot.
package ${snakeCase(speck.name)}

import (
	"encoding/json"
	"net/http"
)

func RegisterHandlers(mux *http.ServeMux, m *${structName}) {
${handlers}

	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]any{"status": "ok", "machine": "${goName(speck.name)}"})
	})

	mux.HandleFunc("GET /state.json", auth(func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(m)
	}))
}
`;
}



function emitStore(speck: SpeckNode): string {
  const structName = `${goName(speck.name)}Machine`;
  return `// Code generated by speckl (go backend): JSON snapshot persistence.
package ${snakeCase(speck.name)}

import (
	"encoding/json"
	"net/http"
	"os"
)

// statePath - where the machine snapshot lives (GB_STATE_PATH, default ./state.json).
func statePath() string {
	if p := os.Getenv("GB_STATE_PATH"); p != "" {
		return p
	}
	return "./state.json"
}

// Save writes a full state snapshot (including the event log).
func (m *${structName}) Save() {
	b, err := json.Marshal(m)
	if err != nil {
		return
	}
	os.WriteFile(statePath(), b, 0600)
}

// Load restores a previous state snapshot. Missing file = fresh machine.
func (m *${structName}) Load() {
	b, err := os.ReadFile(statePath())
	if err != nil {
		return
	}
	json.Unmarshal(b, m)
}

// auth - API-key middleware. If GB_API_KEY is unset, requests are allowed
// (single-operator mode). Set GB_API_KEY to lock actions down.
func auth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		key := os.Getenv("GB_API_KEY")
		if key == "" || r.Header.Get("X-API-Key") == key {
			next(w, r)
			return
		}
		http.Error(w, "unauthorized", http.StatusUnauthorized)
	}
}
`;
}



function emitMain(speck: SpeckNode): string {
  const structName = `${goName(speck.name)}Machine`;
  const goNameS = goName(speck.name);
  return `// Code generated by speckl (go backend): deployable service entrypoint.
//
// Env:
//   PORT          listen port (default 8080)
//   GB_API_KEY    if set, actions require X-API-Key header
//   GB_STATE_PATH state file (default ./state.json)
//
// Deploy: ships with a Dockerfile — any container host works (Railway,
// Fly, Compose). Single static binary, SQLite-free by default.
package main

import (
	"log"
	"net/http"
	"os"

	machine "speckl/${snakeCase(speck.name)}"
)

func main() {
	m := machine.New${goNameS}Machine()
	m.Load()

	mux := http.NewServeMux()
	machine.RegisterHandlers(mux, m)

	addr := ":" + orDefault(os.Getenv("PORT"), "8080")
	log.Printf("speckl ${snakeCase(speck.name)}: listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}

func orDefault(v, d string) string {
	if v == "" {
		return d
	}
	return v
}

var _ = machine.${structName}{}
`;
}


function emitDockerfile(speck: SpeckNode): string {
  const pkg = snakeCase(speck.name);
  return `FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY *.go ./
RUN go build -o /out/server .

FROM alpine:3.20
COPY --from=build /out/server /usr/local/bin/server
ENV PORT=8080 GB_STATE_PATH=/data/state.json
VOLUME /data
EXPOSE 8080
CMD ["/out/server"]
`;
}


// ─── helpers ────────────────────────────────────────────────────────

function memberKey(m: MemberNode): string {
  if (m.type === 'action') return `action:${m.name}`;
  if (m.type === 'event') return `event:${m.name}`;
  if (m.type === 'interface') return `interface:${m.name}`;
  if (m.type === 'state') return 'state';
  if (m.type === 'init') return 'init';
  if (m.type === 'provenance') return 'provenance';
  if (m.type === 'bom') return 'bom';
  if (m.type === 'input') return 'input';
  if (m.type === 'output') return 'output';
  if (m.type === 'verify') return `verify:${(m as any).temporalExpr || ''}`;
  if (m.type === 'constraint') return `constraint:${(m as any).expr || ''}`;
  if (m.type === 'oneof') return `oneof:${(m as any).name || ''}`;
  if (m.type === 'transition') return `transition:${(m as any).name || ''}`;
  if (m.type === 'service') return `service:${(m as any).name || ''}`;
  return m.type;
}

function isEmptyStub(m: MemberNode): boolean {
  if (m.type === 'state') return m.variables.length === 0;
  if (m.type === 'init') return m.assignments.length === 0;
  if (m.type === 'action') return m.statements.length === 0;
  if (m.type === 'event') return m.fields.length === 0;
  if (m.type === 'interface') return m.methods.length === 0;
  if (m.type === 'provenance') return m.clauses.length === 0;
  if (m.type === 'bom') return !m.compiler && !m.solver && !m.runtime;
  return false;
}

function cleanName(s: string): string { return s.replace(/,$/, '').trim(); }
function cleanExpr(s: string): string { return s.replace(/,$/, '').trim(); }
function escapeRegex(s: string): string { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

function goName(s: string): string {
  return s.split(/[^a-zA-Z0-9]+/).filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}
function camelCase(s: string): string {
  const c = goName(s);
  return c.charAt(0).toLowerCase() + c.slice(1);
}
function snakeCase(s: string): string {
  return s.replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .replace(/([a-zA-Z])(\d)/g, '$1_$2')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toLowerCase()
    .replace(/_+/g, '_').replace(/^_|_$/g, '');
}

function defaultGoValue(typeExpr: any): string {
  if (!typeExpr) return 'nil';
  if (typeExpr.type === 'primitive') {
    switch (typeExpr.name) {
      case 'Nat': case 'Int': case 'Date': return '0';
      case 'Real': case 'Number': return '0.0';
      case 'Bool': return 'false';
      case 'String': return '""';
      default: return 'nil';
    }
  }
  if (typeExpr.type === 'list') return `[]${goType(typeExpr.elementType, '', new Map())}{}`;
  if (typeExpr.type === 'set') return `map[${goType(typeExpr.elementType, '', new Map())}]bool{}`;
  if (typeExpr.type === 'map') return `map[${goType(typeExpr.keyType, '', new Map())}]${goType(typeExpr.valueType, '', new Map())}{}`;
  return 'nil';
}