import { AST, SpeckNode, MemberNode, StateNode, InitNode, ActionNode, ConstraintNode, EventNode } from '../parser.js';
import fs from 'fs';
import path from 'path';

/**
 * Generate Go from a SpeckDL spec.
 *
 * Outputs a self-contained Go package with:
 *  - State struct + machine with action methods returning (ret, err)
 *  - Guards (require) become errors; emits append to an event log
 *  - Invariant check methods (read-only)
 *  - Event structs
 *  - handlers.go: HTTP + htmx surface, one POST endpoint per action
 *  - go.mod
 *
 * Clean-room: generated from the SpeckDL specification only.
 */

export function generateGo(ast: AST, outputDir: string): void {
  for (const speck of ast.specks) {
    const pkg = snakeCase(speck.name);
    const speckDir = path.join(outputDir, pkg);
    fs.mkdirSync(speckDir, { recursive: true });

    fs.writeFileSync(path.join(speckDir, 'go.mod'), `module speckl/${pkg}\n\ngo 1.22\n`);
    fs.writeFileSync(path.join(speckDir, `${pkg}.go`), emitSpeck(speck));
    fs.writeFileSync(path.join(speckDir, 'handlers.go'), emitHandlers(speck));
    fs.writeFileSync(path.join(speckDir, 'prelude.go'), preludeFile.replace('package __prelude', `package ${pkg}`));
    fs.writeFileSync(path.join(speckDir, 'store.go'), emitStore(speck));
    const cmdDir = path.join(speckDir, 'cmd', 'server');
    fs.mkdirSync(cmdDir, { recursive: true });
    fs.writeFileSync(path.join(cmdDir, 'main.go'), emitMain(speck));
    fs.writeFileSync(path.join(speckDir, 'Dockerfile'), emitDockerfile(speck));
    console.log(`Generated Go package: ${speckDir} (machine + handlers + prelude + store + main + Dockerfile)`);
  }
}

// ─── types ──────────────────────────────────────────────────────────

const preludeFile = `// Code generated by speckl: generic helpers for spec collection expressions.
// These back the collection syntax used by SpeckDL specs (has, in, count).
package __prelude

import (
	"reflect"
	"strconv"
	"strings"
	"time"
)

func mapHas[M ~map[K]V, K comparable, V any](m M, k K) bool { _, ok := m[k]; return ok }
func inSet[K comparable](k K, set map[K]bool) bool { return set[k] }
func setContains[T comparable](set map[T]bool, k T) bool { return set[k] }
func inValues[K comparable, V any](m map[K]V, v V) bool {
	for _, x := range m {
		if any(x) == any(v) {
			return true
		}
	}
	return false
}
func anyMatch[K comparable, V any](m map[K]V, pred func(V) bool) bool {
	for _, v := range m {
		if pred(v) {
			return true
		}
	}
	return false
}
func listAnyMatch[T any](xs []T, pred func(T) bool) bool {
	for _, x := range xs {
		if pred(x) {
			return true
		}
	}
	return false
}
func countWhere[V any](coll []V, pred func(V) bool) int {
	n := 0
	for _, x := range coll {
		if pred(x) {
			n++
		}
	}
	return n
}
func nowString() string { return strconv.FormatInt(time.Now().Unix(), 10) }
func strPtr(s string) *string { return &s }
func mapValues[K comparable, V any](m map[K]V) []V {
	out := make([]V, 0, len(m))
	for _, v := range m {
		out = append(out, v)
	}
	return out
}
func mapKeys[K comparable, V any](m map[K]V) []K {
	out := make([]K, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
func listContains[T comparable](xs []T, v T) bool {
	for _, x := range xs {
		if any(x) == any(v) {
			return true
		}
	}
	return false
}
func strCmp(a, b *string) int {
	if a == nil || b == nil {
		return 0
	}
	return strings.Compare(*a, *b)
}
func anyLen(v any) int {
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Ptr {
		if rv.IsNil() {
			return 0
		}
		rv = rv.Elem()
	}
	switch rv.Kind() {
	case reflect.String, reflect.Slice, reflect.Map:
		return rv.Len()
	}
	return 0
}
func slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b []rune
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b = append(b, r)
		} else if len(b) > 0 && b[len(b)-1] != '-' {
			b = append(b, '-')
		}
	}
	return strings.Trim(string(b), "-")
}
func toInt(v any) int64 {
	switch x := v.(type) {
	case string:
		n, _ := strconv.ParseInt(x, 10, 64)
		return n
	case *string:
		if x == nil { return 0 }
		n, _ := strconv.ParseInt(*x, 10, 64)
		return n
	case int64:
		return x
	}
	return 0
}
`;

function goType(t: any, speckName: string, enumMap: Map<string, string[]>): string {
  if (!t) return 'any';
  if ((t.type as any) === 'union' || Array.isArray(t)) {
    // T | null -> *T
    const members: any[] = t.types ?? t;
    const nonNull = members.find((x: any) => !(x.name === 'null' && x.type !== 'ident') && !(x.type === 'ident' && x.name === 'null'));
    if (nonNull) return '*' + goType(nonNull, speckName, enumMap);
    return 'any';
  }
  if (t.type === 'primitive') {
    const map: Record<string, string> = {
      Nat: 'int64', Int: 'int64', Real: 'float64', Number: 'float64',
      Bool: 'bool', String: 'string', Bytes: '[]byte', Date: 'int64',
    };
    const base = map[t.name] || t.name.toLowerCase();
    return (t as any).nullable ? '*' + base : base;
  }
  if (t.type === 'list') return `[]${goType(t.elementType, speckName, enumMap)}`;
  if (t.type === 'set') return `map[${goType(t.elementType, speckName, enumMap)}]bool`;
  if (t.type === 'map') return `map[${goType(t.keyType, speckName, enumMap)}]${goType(t.valueType, speckName, enumMap)}`;
  if (t.type === 'record') {
    const fields = t.fields.map((f: any) => `${goName(f.name)} ${goType(f.type, speckName, enumMap)}`).join('; ');
    return `struct { ${fields} }`;
  }
  if (t.type === 'ident') {
    const raw = cleanName(t.name);
    if (enumMap?.has(raw)) return `${goName(speckName)}${goName(raw)}`;
    const prim: Record<string, string> = { Nat: 'int64', Int: 'int64', Bool: 'bool', String: 'string', Date: 'int64', Real: 'float64', Number: 'float64' };
    if (prim[raw]) return t.nullable ? '*' + prim[raw] : prim[raw];
    const opt = raw.match(/^Option[_(]\s*(\w+)\s*\)?$/);
    if (opt) return '*' + (prim[opt[1]] || goName(opt[1]));
    return t.nullable ? '*' + goName(raw) : goName(raw);
  }
  return 'any';
}

// ─── expression rewriting ───────────────────────────────────────────

// strip a trailing // comment (outside string literals) from an expression
function stripComment(expr: string): string {
  let inStr = false; let esc = false;
  for (let i = 0; i < expr.length - 1; i++) {
    const ch = expr[i];
    if (esc) { esc = false; continue; }
    if (ch === '\\') { esc = true; continue; }
    if (ch === '"') inStr = !inStr;
    if (!inStr && ch === '/' && expr[i + 1] === '/') return expr.slice(0, i).trim();
  }
  return expr;
}

function rewriteGoExpr(
  expr: string,
  nameMap: Map<string, string>,
  mapVarOrigNames: Set<string>,
  localNames: Set<string>,
  stateEnumName: string,
  knownStateValues: string[],
  localRecords: Map<string, string> = new Map()
): string {
  expr = stripComment(expr);
  // existential quantifier: (not) exists v in coll(.values())?: pred
  const em = expr.match(/(not\s+)?exists\s+(\w+)\s+in\s+([\w.]+?)(?:\.values(?:\(\))?)?:\s*([\s\S]+)$/);
  if (em) {
    let origName = em[3].replace(/^m\./, '');
    for (const [orig, gn] of nameMap) { if (em[3] === gn) { origName = orig; break; } }
    const vt = stateVarTypes.get(origName);
    let rec = 'any';
    if (vt?.type === 'map' && vt.valueType?.type === 'ident') rec = goType(vt.valueType, '', currentEnumMap);
    else if (vt?.type === 'list' && vt.elementType?.type === 'ident') rec = goType(vt.elementType, '', currentEnumMap);
    const helper = vt?.type === 'list' ? 'listAnyMatch' : 'anyMatch';
    expr = `${em[1] ? '!' : ''}${helper}(${em[3]}, func(${em[2]} ${rec}) bool { return ${em[4]} })`;
  }
  let g = expr;
  // Protect string literals: the chain below rewrites bare words (`not`,
  // enum values, `null`) and must never touch string content.
  const stringLits: string[] = [];
  g = g.replace(/"(?:[^"\\]|\\.)*"/g, m2 => { stringLits.push(m2); return `\u0000${stringLits.length - 1}\u0000`; });
  // count(coll, v => pred) -> countWhere(<coll>, func(v T) bool { return pred })
  // Balanced-paren scan: the predicate may contain nested calls, so the
  // old first-')' regex truncated it (syntax errors in the emitted Go).
  // The predicate is emitted verbatim and lowered by the chain below.
  if (/\bcount\(/.test(g)) {
    let out = '';
    let i = 0;
    while (i < g.length) {
      if (!/^\bcount\(/.test(g.slice(i))) { out += g[i]; i++; continue; }
      let depth = 0, close = -1, inStr = false;
      for (let k = i; k < g.length; k++) {
        const ch = g[k];
        if (ch === '"') inStr = !inStr;
        if (inStr) continue;
        if (ch === '(') depth++;
        else if (ch === ')') { depth--; if (depth === 0) { close = k; break; } }
      }
      if (close < 0) { out += g[i]; i++; continue; }
      const inner = g.slice(i + 'count('.length, close);
      let d2 = 0, b2 = 0, cIdx = -1;
      for (let k = 0; k < inner.length; k++) {
        const ch = inner[k];
        if (ch === '(' || ch === '<' || ch === '[') d2++;
        else if (ch === ')' || ch === '>' || ch === ']') d2--;
        else if (ch === '{') b2++;
        else if (ch === '}') b2--;
        else if (ch === ',' && d2 === 0 && b2 === 0) { cIdx = k; break; }
      }
      const lm = cIdx >= 0 ? inner.slice(cIdx + 1).trim().match(/^(\w+)\s*=>\s*([\s\S]+)$/) : null;
      if (cIdx < 0 || !lm) { out += g.slice(i, close + 1); i = close + 1; continue; }
      const coll = inner.slice(0, cIdx).trim();
      const baseVar = coll.replace(/\.values\(\)|\.keys\(\)/g, '').trim();
      const vt = stateVarTypes.get(baseVar) || stateVarTypes.get(cleanName(baseVar));
      let elemT = 'any';
      if (vt?.type === 'map' && vt.valueType) elemT = goType(vt.valueType, '', currentEnumMap);
      else if (vt?.type === 'list' && vt.elementType) elemT = goType(vt.elementType, '', currentEnumMap);
      out += `countWhere(${coll.replace(/\.values\(\)|\.keys\(\)/g, '')}, func(${lm[1]} ${elemT}) bool { return ${lm[2].trim()} })`;
      i = close + 1;
    }
    g = out;
  }

  const lengthLower = (arg: string): string => {
    const dm = arg.trim().match(/^([A-Za-z_]\w*)\.([A-Za-z_]\w*)$/);
    if (dm) {
      const rec = localRecords.get(dm[1]);
      let ft = rec ? recordFieldTypes.get(rec)?.get(dm[2]) : undefined;
      // the base object may be a state variable holding a record
      if (!ft) {
        const vt = stateVarTypes.get(dm[1]);
        if (vt?.type === 'ident') ft = recordFieldTypes.get(cleanName(vt.name))?.get(dm[2]);
      }
      const base = goType({ ...ft, nullable: false }, '', new Map());
      // anyLen handles plain strings and *string (nil-safe) alike; int64
      // because Nat values compare against it
      if (ft && base === 'string') return `int64(anyLen(${arg}))`;
    }
    return `int64(len(${arg}))`;
  };
  const shouldPrefix = (ident: string) => nameMap.has(ident) && !localNames.has(ident);
  const goify = (ident: string) => nameMap.has(ident) && !localNames.has(ident) ? `m.${nameMap.get(ident)}` : ident;

  g = g
    .replace(/Date\.now\(\)\.toString\(\)/g, 'nowString()')
    .replace(/Date\.now\(\)/g, 'time.Now().Unix()')
    .replace(/\bnow\(\)/g, 'time.Now().Unix()')
    .replace(/\btoInt\(([^)]+)\)/g, 'toInt($1)')
    .replace(/\blength\(([^)]+)\)/g, (_, a) => lengthLower(a))
    .replace(/\blen\(([^)]+)\)/g, (_, a) => lengthLower(a))
    .replace(/\bjoin\(([^,]+),\s*([^)]+)\)/g, 'strings.Join($1, $2)')
    .replace(/\bappend\(([^,]+),\s*([^)]+)\)/g, 'append($1, $2)')
    .replace(/(\w+)\.has\(([^)]+)\)/g, 'mapHas($1, $2)')
    .replace(/\((\w+)\[([^\]]+)\]\)\.has\(([^)]+)\)/g, (_m, coll, key, v) => {
      const vt = stateVarTypes.get(cleanName(coll));
      const isList = vt?.type === 'map' && vt.valueType?.type === 'list';
      return isList ? `listContains(${coll}[${key}], ${v})` : `mapHas(${coll}[${key}], ${v})`;
    })
    .replace(/([\w.]+)\.contains\(([^)]+)\)/g, 'listContains($1, $2)')
    .replace(/\bcount\(([^,]+),\s*(\w+)\s*=>\s*([^)]+)\)/g, 'countWhere($1, func($2 any) bool { return $3 })');
// (legacy count lowering superseded by the balanced-paren scanner above)

  // state enum literals -> typed consts (skip field accesses `x.passed`,
  // record-literal keys `registered:`, and quoted strings)
  for (const [val, constName] of enumValueConsts) {
    g = g.replace(new RegExp('(?<![.\\w])' + escapeRegex(val) + '(?![\\w":])', 'g'), constName);
  }

  // identifier prefixing
  g = g.split(/([\s()\[\]{}+\-*/=<>!&|.,;:'"`]+)/).map(tok => {
    if (/^(true|false|nil|null|not|and|or|in|notIn|old|forall|let|if|else|time|fmt|strings)$/.test(tok)) return tok;
    if (/^\d+(\.\d+)?$/.test(tok)) return tok;
    if (/^[a-zA-Z_]\w*$/.test(tok) && shouldPrefix(tok)) return goify(tok);
    return tok;
  }).join('');
  g = g.replace(/\]\.m\.(\w+)/g, '].$1');

  // speckdl patterns -> go
  g = g
    .replace(/([\w.\u0000]+)\.startsWith\(([^()]*)\)/g, 'strings.HasPrefix($1, $2)')
    .replace(/([\w.\u0000]+)\.endsWith\(([^()]*)\)/g, 'strings.HasSuffix($1, $2)')
    .replace(/([\w.\u0000]+)\s+starts with\s+("[^"]*"|\u0000\d+\u0000|[\w.]+)/g, 'strings.HasPrefix($1, $2)')
    .replace(/([\w.\u0000]+)\s+ends with\s+("[^"]*"|\u0000\d+\u0000|[\w.]+)/g, 'strings.HasSuffix($1, $2)')
    .replace(/(\w+)\.append\(([^()]*)\)/g, 'append($1, $2)')
    .replace(/(\w+)\s+notIn\s+(\w+)\.keys/g, '!mapHas($2, $1)')
    .replace(/(\w+)\s+in\s+(\w+)\.keys/g, 'mapHas($2, $1)')
    .replace(/(\w+)\s+notIn\s+(\w+)\.values/g, '!inValues($2, $1)')
    .replace(/(\w+)\s+in\s+(\w+)\.values/g, 'inValues($2, $1)')
    .replace(/\bnot\s*\(/g, '!(')
    .replace(/old\(([^()]*(?:\([^()]*\)[^()]*)*)\)/g, '$1')
    .replace(/\.size\(\)/g, '.len')
    .replace(/\b===\b/g, '==')
    .replace(/([A-Za-z_]\w*)\s*(==|!=)\s*null\b/g, (m2, v, op) =>
      currentLetStringVars.has(v) ? `${v} ${op} ""` : m2);

  // bare map var bracket access -> m.field[k]
  for (const mapVar of mapVarOrigNames) {
    const gname = nameMap.get(mapVar) || camelCase(mapVar);
    const bare = new RegExp(`(?<![\\w.])${escapeRegex(mapVar)}\\[`, 'g');
    g = g.replace(bare, `m.${gname}[`);
  }

  // set membership: target in { "a", "b", "c" } -> (target == "a" || target == "b" || target == "c")
  g = g.replace(/([\w.]+)\s+in\s+\{([^}]+)\}/g, (_, ident, values) => {
    const vals = values.split(',').map((v: string) => v.trim().replace(/"/g, ''));
    return '(' + vals.map((v: string) => `${ident} == ${JSON.stringify(v)}`).join(' || ') + ')';
  });

  // array membership: target in [ "a", "b" ] -> (target == "a" || target == "b")
  g = g.replace(/([\w.]+)\s+in\s+\[([^\]]+)\]/g, (_, ident, values) => {
    const vals = values.split(',').map((v: string) => v.trim());
    return '(' + vals.map((v: string) => `${ident} == ${v}`).join(' || ') + ')';
  });

  // nullable record fields compared with string literals deref the pointer
  // (the enclosing implies/|| guards nil first; Go short-circuits)
  g = g.replace(/([A-Za-z_]\w*)\.([A-Za-z_]\w*)\s*(==|!=)\s*(\u0000\d+\u0000)/g, (m2, o, f, op, ph) => {
      const rec = localRecords.get(o);
      const ft = rec ? recordFieldTypes.get(rec)?.get(f) : undefined;
      if (ft?.nullable && goType({ ...ft, nullable: false }, '', new Map()) === 'string') {
        return `*${o}.${goFieldRenames.get(f) || goName(f)} ${op} ${ph}`;
      }
      return m2;
    });

  // non-nullable record fields cannot compare against nil; compare with ""
  g = g.replace(/([A-Za-z_]\w*)\.([A-Za-z_]\w*)\s*(==|!=)\s*null\b/g, (m2, o, f, op) => {
      const rec = localRecords.get(o);
      const ft = rec ? recordFieldTypes.get(rec)?.get(f) : undefined;
      if (ft && !ft.nullable && goType({ ...ft, nullable: false }, '', new Map()) === 'string') {
        return `${o}.${goFieldRenames.get(f) || goName(f)} ${op} ""`;
      }
      return m2;
    })
    .replace(/\bnull\b/g, 'nil')
    .replace(/([\w.]+)\.values\(\)/g, 'mapValues($1)')
    .replace(/([\w.]+)\.keys\(\)/g, 'mapKeys($1)');

  // record-field string comparisons with mixed nullability: deref the
  // nullable side (implies guards usually precede; Go short-circuits ||)
  g = g.replace(/([\w.]+)\.([A-Za-z_]\w*)\s*(==|!=)\s*([\w.]+)\.([A-Za-z_]\w*)/g, (m2, o1, f1, op, o2, f2) => {
    const fieldTypeOf = (obj: string, field: string): any => {
      const rec = localRecords.get(obj);
      if (rec) return recordFieldTypes.get(rec)?.get(field);
      // machine-prefixed state vars: m.<GoName> -> raw state name
      let vt = stateVarTypes.get(obj);
      if (!vt && obj.startsWith('m.')) {
        const rev = new Map(Array.from(nameMap).map(([raw, gn]) => [gn, raw]));
        const rawName = rev.get(obj.slice(2));
        if (rawName !== undefined) vt = stateVarTypes.get(rawName);
      }
      if (vt?.type === 'ident') return recordFieldTypes.get(cleanName(vt.name))?.get(field);
      if (vt?.type === 'record') {
        for (const f of (vt.fields || [])) if (f.name === field) return f.type;
      }
      return undefined;
    };
    const t1 = fieldTypeOf(o1, f1);
    const t2 = fieldTypeOf(o2, f2);
    if (!t1 || !t2) return m2;
    const isStr = (t: any) => goType({ ...t, nullable: false }, '', new Map()) === 'string';
    if (!isStr(t1) || !isStr(t2)) return m2;
    const d1 = t1.nullable ? '*' : '';
    const d2 = t2.nullable ? '*' : '';
    if (!d1 && !d2) return m2;
    return `${d1}${o1}.${goFieldRenames.get(f1) || goName(f1)} ${op} ${d2}${o2}.${goFieldRenames.get(f2) || goName(f2)}`;
  });

  // implies -> !(p) || (q)
  let changed = true;
  while (changed) {
    changed = false;
    g = g.replace(/implies\s*\(([^,()]*(?:\([^()]*\)[^()]*)*),\s*([^()]*(?:\([^()]*\)[^()]*)*)\)/g, (_, p, q) => {
      changed = true;
      return `(!(${p.trim()}) || (${q.trim()}))`;
    });
  }
  g = g.replace(/\bnot\s+([a-zA-Z_]\w*)/g, '!$1');
  // forall cannot be an expression in Go; lower at the invariant-statement level.
  // Any residual forall is surfaced as a visible TODO, never silently dropped.
  if (/forall/.test(g)) g = `/* UNLOWERED forall - manual attention required: ${g.replace(/\*\//g, '* /')} */ true`;
  // nullable string comparisons: a.x > b.y -> strCmp(a.x, b.y) > 0
  g = g.replace(/([A-Za-z_]\w*)\.([A-Za-z_]\w*)\s*(>=|<=|>|<)\s*([A-Za-z_]\w*)\.([A-Za-z_]\w*)/g, (m2, o1, f1, op, o2, f2) => {
    const r1 = localRecords.get(o1);
    const r2 = localRecords.get(o2);
    const t1 = r1 ? recordFieldTypes.get(r1)?.get(f1) : undefined;
    const t2 = r2 ? recordFieldTypes.get(r2)?.get(f2) : undefined;
    const isStr = (t: any) => !!t && goType({ ...t, nullable: false }, '', new Map()) === 'string';
    const isPtr = (t: any) => !!t?.nullable;
    if (isStr(t1) && isStr(t2)) {
      const a = `${o1}.${goFieldRenames.get(f1) || goName(f1)}`;
      const b = `${o2}.${goFieldRenames.get(f2) || goName(f2)}`;
      const l = isPtr(t1) ? a : `&${a}`;
      const r = isPtr(t2) ? b : `&${b}`;
      return `strCmp(${l}, ${r}) ${op} 0`;
    }
    return m2;
  });

  // record field casing: .column -> .Column (known record fields)
  for (const [lower, G] of goFieldRenames) {
    g = g.replace(new RegExp(`\\.${lower}\\b`, 'g'), `.${G}`);
  }
  // record literal field casing: Project { projectId: v } -> Project { ProjectId: v }
  for (const [typeName, fields] of recordTypes) {
    const fieldKeys = fields.map(f => escapeRegex(f)).join('|');
    const re = new RegExp(`\\b${typeName}\\s*\\{([^{}]*)\\}`, 'g');
    g = g.replace(re, (m2, inner) => {
      // case field names, then wrap nullable-string field values with strPtr
      const cased = inner.replace(new RegExp(`\\b(${fieldKeys})\\s*:`, 'g'), (_m: string, f: string) => `${goName(f)}:`);
      const ftmapRaw = recordFieldTypes.get(cleanName(typeName));
      if (!ftmapRaw) return `${typeName}{ ${cased} }`;
      // case-insensitive field-type lookup (the pass just cased field names)
      const ftmap = new Map(Array.from(ftmapRaw).map(([k, v]) => [k.toLowerCase(), v]));
      // split at top-level commas (honoring strings)
      const parts: string[] = [];
      let d = 0, inStr = false, start = 0;
      for (let k = 0; k < cased.length; k++) {
        const ch = cased[k];
        if (ch === '"') inStr = !inStr;
        if (inStr) continue;
        if (ch === '(' || ch === '[' || ch === '{') d++;
        else if (ch === ')' || ch === ']' || ch === '}') d--;
        else if (ch === ',' && d === 0) { parts.push(cased.slice(start, k)); start = k + 1; }
      }
      parts.push(cased.slice(start));
      const wrapped = parts.map(part => {
        const pm = part.match(/^\s*([A-Za-z_]\w*)\s*:\s*([\s\S]*)$/);
        if (!pm) return part;
        const ft = ftmap.get(pm[1].toLowerCase());
        const v = pm[2].trim();
        if (ft?.nullable && goType({ ...ft, nullable: false }, '', new Map()) === 'string'
            && v !== 'nil' && !(v.match(/^[A-Za-z_]\w*$/) && currentNullableVars.has(v))) {
          return `${goName(pm[1])}: strPtr(${v})`;
        }
        return part;
      });
      return `${typeName}{ ${wrapped.join(', ')} }`;
    });
  }
  g = g.replace(/\u0000(\d+)\u0000/g, (_m, n) => stringLits[+n]);
  return g.trim();
}

function goImplications(expr: string): string {
  let e = expr; let changed = true;
  while (changed) {
    changed = false;
    let out = '';
    let i = 0;
    while (i < e.length) {
      if (/^\bimplies\(/.test(e.slice(i))) {
        let depth = 0, close = -1;
        for (let k = i; k < e.length; k++) {
          if (e[k] === '(') depth++;
          else if (e[k] === ')') { depth--; if (depth === 0) { close = k; break; } }
        }
        if (close < 0) { out += e[i]; i++; continue; }
        const inner = e.slice(i + 'implies('.length, close);
        let d = 0, cIdx = -1;
        for (let k = 0; k < inner.length; k++) {
          if (inner[k] === '(') d++;
          else if (inner[k] === ')') d--;
          else if (inner[k] === ',' && d === 0) { cIdx = k; break; }
        }
        if (cIdx < 0) { out += e.slice(i, close + 1); i = close + 1; continue; }
        out += `(!(${inner.slice(0, cIdx).trim()}) || (${inner.slice(cIdx + 1).trim()}))`;
        changed = true;
        i = close + 1;
        continue;
      }
      out += e[i]; i++;
    }
    e = out;
  }
  // infix implies: A implies B -> (!(A) || (B))  (split at paren depth 0, recursive)
  const lowerInfixImplies = (s: string): string => {
    let depth = 0;
    for (let i = 0; i < s.length; i++) {
      const ch = s[i];
      if (ch === '(') depth++;
      else if (ch === ')') depth--;
      else if (depth === 0 && s.startsWith('implies', i)
        && (i === 0 || /\s/.test(s[i - 1]))
        && (s[i + 7] === undefined || /\s/.test(s[i + 7]))) {
        const left = lowerInfixImplies(s.slice(0, i).trim());
        const right = lowerInfixImplies(s.slice(i + 7).trim());
        return `(!(${left}) || (${right}))`;
      }
    }
    return s;
  };
  e = lowerInfixImplies(e);
  e = e.replace(/\bnot\s+([a-zA-Z_]\w*)/g, '!$1');
  e = e.replace(/\bor\b/g, '||').replace(/\band\b/g, '&&');
  return e;
}

// ─── speck emission ─────────────────────────────────────────────────

let goFieldRenames: Map<string, string> = new Map();
let enumValueConsts: Map<string, string> = new Map();
let recordFieldTypes: Map<string, Map<string, any>> = new Map();
let currentEnumMap: Map<string, string[]> = new Map();
let stateVarTypes: Map<string, any> = new Map();
let recordTypes: Map<string, string[]> = new Map();
let currentFnRetTypes: Map<string, string> = new Map();
let currentLetStringVars: Set<string> = new Set();
let currentNullableVars: Set<string> = new Set();
function stateVarsOf(name: string): string {
  const t = stateVarTypes.get(name);
  if (t && t.type === 'list') return goType(t.elementType, 'Spot', new Map());
  return 'any';
}
// Map { "k" -> v, ... } -> map[K]V{ "k": v, ... } for a map-typed target.
function lowerMapLiteral(val: string, vt: any): string | null {
  const m = val.match(/^Map\s*\{([\s\S]*)\}$/);
  if (!m || vt?.type !== 'map') return null;
  const keyT = goType(vt.keyType, '', currentEnumMap);
  const valT = goType(vt.valueType, '', currentEnumMap);
  // split pairs at top-level commas
  const pairs: string[] = [];
  let d = 0, inStr = false, start = 0;
  const inner = m[1];
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i];
    if (ch === '"') inStr = !inStr;
    if (inStr) continue;
    if (ch === '(' || ch === '[' || ch === '{') d++;
    else if (ch === ')' || ch === ']' || ch === '}') d--;
    else if (ch === ',' && d === 0) { pairs.push(inner.slice(start, i)); start = i + 1; }
  }
  pairs.push(inner.slice(start));
  const entries = pairs.map(p => {
    const am = p.split('->');
    if (am.length !== 2) return null;
    return `${am[0].trim()}: ${am[1].trim()}`;
  }).filter(Boolean);
  return `map[${keyT}]${valT}{ ${entries.join(', ')} }`;
}

function fixRecordLiteral(expr: string, elemType: string): string {
  // uppercase record literal fields: CardEvent { cardId: x } -> CardEvent{ CardId: x }
  const m = expr.match(/^(\w+)\s*\{([\s\S]*)\}$/);
  if (!m) return expr;
  const inner = m[2].replace(/(\w+)\s*:/g, (_, f) => `${goName(f)}:`);
  return `${m[1]}{ ${inner} }`;
}

function emitSpeck(speck: SpeckNode): string {
  stateVarTypes = new Map();
  for (const m of speck.members) {
    if (m.type === 'state') for (const v of (m as any).variables) stateVarTypes.set((v as any).name, v.typeExpr);
  }
  const deduped = new Map<string, MemberNode>();
  for (const m of speck.members) {
    const key = memberKey(m);
    const existing = deduped.get(key);
    if (!existing || isEmptyStub(existing)) deduped.set(key, m);
  }
  const members = Array.from(deduped.values());

  // Merge all state members (multiple entities per speck)
  const stateNodes = members.filter(m => m.type === 'state') as StateNode[];
  let mergedState: any = undefined;
  if (stateNodes.length > 0) {
    mergedState = { type: 'state', variables: stateNodes.flatMap(function(n) { return n.variables; }) } as any;
  }
  const stateNode: any = mergedState;
  const initNodes = members.filter(m => m.type === 'init') as any[];  const initNode: any = initNodes.length > 0 ? {
    type: 'init',
    assignments: initNodes.flatMap(function(n) { return n.assignments; }),
  } : undefined;
  const actions = members.filter(m => m.type === 'action') as ActionNode[];
  const events = members.filter(m => m.type === 'event') as EventNode[];
  const constraints = members.filter(m => m.type === 'constraint') as ConstraintNode[];
  const allInterfaces = members.filter(m => m.type === 'interface') as any[];

  const enumMap = new Map<string, string[]>();
  for (const iface of allInterfaces) {
    if (iface?.methods?.length > 0) enumMap.set(iface.name, iface.methods.map((m: any) => m.name));
  }
  currentEnumMap = enumMap;

  const goNameS = goName(speck.name);
  const speckName = speck.name;
  const structName = `${goNameS}Machine`;

  // state enum
  const stateVarType = stateNode?.variables?.[0]?.typeExpr;
  let stateEnumName = `${goNameS}State`;
  if (stateVarType?.type === 'ident' && stateVarType.name) {
    stateEnumName = `${goNameS}${goName(cleanName(stateVarType.name))}`;
  } else if (enumMap.size > 0) {
    const first = enumMap.keys().next().value;
    if (first) stateEnumName = `${goNameS}${goName(first)}`;
  }

  const stateVars: { origName: string; goName: string; typeExpr: any }[] =
    ((stateNode?.variables ?? []) as any[]).map((v: any) => ({
    origName: cleanName(v.name),
    goName: goName(cleanName(v.name)),   // exported so JSON snapshot persistence works
    typeExpr: v.typeExpr,
  }));
  const nameMap = new Map<string, string>();
  for (const v of stateVars) nameMap.set(v.origName, v.goName);
  const stateVarOrigNames = new Set(stateVars.map(v => v.origName));
  const mapVarOrigNames = new Set(stateVars
    .filter(v => v.typeExpr?.type === 'map' || (v.typeExpr?.type === 'ident' && v.typeExpr?.name && /^Map/i.test(v.typeExpr.name)))
    .map(v => v.origName));

  // collect record field renames + record literal casing tables (BEFORE rewrites)
  goFieldRenames = new Map();
  recordTypes = new Map();
  for (const m of members) {
    if (m.type === 'interface' && (m as any).fields) {
      recordTypes.set(goName(m.name), (m as any).fields.map((f: any) => f.name));
      recordFieldTypes.set(cleanName(m.name), new Map((m as any).fields.map((f: any) => [f.name, f.type])));
      for (const f of (m as any).fields) goFieldRenames.set(f.name, goName(f.name));
    }
    if ((m.type as any) === 'type' && (m as any).typeExpr?.type === 'record') {
      const fields = (m as any).typeExpr.fields.map((f: any) => f.name);
      recordTypes.set(goName((m as any).name), fields);
      recordFieldTypes.set(cleanName((m as any).name), new Map((m as any).typeExpr.fields.map((f: any) => [f.name, f.type])));
      for (const f of fields) goFieldRenames.set(f.name, goName(f.name));
    }
  }

  // collect known state values (enum interfaces + string literals compared/emitted)
  const known = new Set<string>();
  for (const vals of enumMap.values()) for (const v of vals) known.add(v);
  // DO NOT infer enums from string literals in actions — this causes
  // type pollution in multi-entity specs. Only explicit interface enums
  // should generate typed constants.
  const knownStateValues = Array.from(known);

  // enum defs
  const enumDefs: string[] = [];
  const seenEnumTypes = new Map<string, string[]>();
  // Seed the state-enum name only when the first state variable's type is
  // actually one of the interface enums. Specs whose first state var is a
  // record (e.g. LlmRouting) would otherwise hijack every enum's constants
  // under the wrong type name.
  const firstVarIsEnum = stateVarType?.type === 'ident' && enumMap.has(cleanName(stateVarType.name));
  if (knownStateValues.length > 0 && firstVarIsEnum) seenEnumTypes.set(stateEnumName, knownStateValues);
  for (const [k, v] of enumMap) seenEnumTypes.set(`${goNameS}${goName(k)}`, v);
  for (const [typeName, values] of seenEnumTypes) {
    enumDefs.push(`type ${typeName} string\n`);
    for (const v of Array.from(new Set(values))) {
      enumDefs.push(`const ${typeName}${goName(v)} ${typeName} = ${JSON.stringify(v)}`);
    }
    enumDefs.push('');
  }

  // value -> typed const name, for lowering bare enum literals in expressions
  enumValueConsts = new Map();
  for (const [typeName, values] of seenEnumTypes) {
    for (const v of values) if (!enumValueConsts.has(v)) enumValueConsts.set(v, `${typeName}${goName(v)}`);
  }

  const recordStructs = allInterfaces
    .filter(iface => iface?.kind === 'record' || (iface?.fields && iface.fields.length > 0))
    .map(iface => {
      const fields = iface.fields.map((f: any) => `${goName(f.name)} ${goType(f.type, speck.name, enumMap)}`).join('; ');
      return `type ${goName(iface.name)} struct { ${fields} }`;
    }).join('\n\n');

  const eventStructs = events.map(e => {
    const fields = e.fields.map(f => `${goName(f.name)} ${goType(f.type, speckName, enumMap)}`).join('; ');
    return `type ${goName(e.name)} struct { ${fields} }`;
  }).join('\n\n');

  const stateFields = stateVars.map(v => `${v.goName} ${goType(v.typeExpr, speckName, enumMap)}`).join('\n\t');

    // init: concrete empties for ALL state vars first (nil maps panic on
  // assignment), then apply explicit init assignments as overrides.
  const defaults = stateVars
    .map(v => `\tm.${v.goName} = ${defaultGoValue(v.typeExpr, speck.name, enumMap)}`)
    .join('\n');
  const overrides = ((initNode?.assignments ?? []) as any[])
    .filter((a: any) => !/^\w*\.(empty|now)/.test(cleanExpr(a.expr)))
    .map((a: any) => {
      const gname = nameMap.get(cleanName(a.name)) || camelCase(cleanName(a.name));
      let expr = rewriteGoExpr(cleanExpr(a.expr), nameMap, mapVarOrigNames, new Set<string>(), stateEnumName, knownStateValues);
      const ml = lowerMapLiteral(expr, stateVarTypes.get(cleanName(a.name)));
      if (ml) expr = ml;
      return `\tm.${gname} = ${expr}`;
    }).join('\n');
  const initBody = overrides ? defaults + '\n' + overrides : defaults;

  // unknown domain functions -> explicit stubs (return type inferred from usage)
  const unknown = new Set<string>();
  const builtin = new Set(['now', 'len', 'length', 'join', 'append', 'mapHas', 'setContains', 'inValues', 'countWhere', 'implies', 'slugify', 'contains', 'has', 'values', 'keys', 'empty', 'size', 'count']);
  const ctxExprs: { text: string; ctx: 'guard' | 'value' | 'emit' | 'return' }[] = [];
  const letVarFn = new Map<string, string>();
  for (const a of actions) {
    for (const st of a.statements) {
      const ctx = (st.type === 'require' || st.type === 'precondition') ? 'guard'
        : st.type === 'emit' ? 'emit' : st.type === 'return' ? 'return' : 'value';
      ctxExprs.push({ text: String((st as any).expr ?? ''), ctx });
      if (st.type === 'ifblock') ctxExprs.push({ text: String((st as any).raw ?? ''), ctx: 'value' });
      if (st.type === 'emit') for (const f of (st as any).fields ?? []) {
        ctxExprs.push({ text: String(f.value), ctx: 'emit' });
      }
      if (st.type === 'assign') ctxExprs.push({ text: String((st as any).target ?? ''), ctx: 'value' });
      if (st.type === 'let') {
        const m = String((st as any).expr ?? '').trim().match(/^([a-z_]\w*)\s*\(/);
        if (m && !builtin.has(m[1])) letVarFn.set(String((st as any).name), m[1]);
      }
      if (st.type === 'ifblock') {
        const raw = String((st as any).raw ?? '');
        for (const lm of raw.matchAll(/let\s+(\w+)\s*:=\s*([a-z_]\w*)\s*\(/g)) {
          if (!builtin.has(lm[2])) letVarFn.set(lm[1], lm[2]);
        }
      }
    }
  }
  for (const c of constraints) ctxExprs.push({ text: String((c as any).expr ?? ''), ctx: 'guard' });

  const numFns = new Set<string>();
  const boolFns = new Set<string>();
  const strFns = new Set<string>();
  for (const { text, ctx } of ctxExprs) {
    for (const m of text.match(/\b([a-z_]\w*)\s*\(/g) ?? []) {
      const fn = m.replace(/\s*\($/, '');
      if (builtin.has(fn)) continue;
      unknown.add(fn);
      if (ctx === 'guard') boolFns.add(fn);
    }
  }
  // let-bound call results: infer return type from how the variable is used
  for (const [v, fn] of letVarFn) {
    const varRe = new RegExp(`\\b${escapeRegex(v)}\\b`);
    for (const { text } of ctxExprs) {
      if (!varRe.test(text)) continue;
      if (new RegExp(`(>=|<=|>|<)\\s*${escapeRegex(v)}\\b`).test(text)
        || new RegExp(`\\b${escapeRegex(v)}\\s*(>=|<=|>|<)`).test(text)) { numFns.add(fn); continue; }
      if (/(==|!=)\s*(true|false)\b/.test(text)) boolFns.add(fn);
    }
    for (const { text } of ctxExprs) {
      if (!varRe.test(text)) continue;
      if (new RegExp(`\\w+\\s*:\\s*${escapeRegex(v)}\\b`).test(text) || new RegExp(`\\w+\\.\\w+\\s*:=\\s*${escapeRegex(v)}\\b`).test(text)) strFns.add(fn);
      // map-key usage implies a string-typed domain function
      if (new RegExp(`\\[\\s*${escapeRegex(v)}\\s*\\]`).test(text)) strFns.add(fn);
    }
  }
  // direct call comparisons: x == fn(...) / fn(...) >= y
  for (const fn of Array.from(unknown)) {
    const callCmp = new RegExp(`(>=|<=|>|<|==|!=)\\s*${escapeRegex(fn)}\\s*\\(|${escapeRegex(fn)}\\s*\\([^)]*\\)\\s*(>=|<=|>|<|==|!=)`);
    for (const { text } of ctxExprs) {
      if (!callCmp.test(text)) continue;
      if (/(==|!=)\s*(true|false)\b/.test(text)) boolFns.add(fn);
      else numFns.add(fn);
    }
  }
  const fnKind = (fn: string): string => numFns.has(fn) ? 'float64' : boolFns.has(fn) ? 'bool' : strFns.has(fn) ? 'string' : 'any';
  currentFnRetTypes = new Map(Array.from(unknown).map(fn => [fn, fnKind(fn)]));
  const stubs = unknown.size > 0
    ? Array.from(unknown).sort().map(fn => {
        const ret = fnKind(fn);
        return `// ${fn} - domain function from the SpeckDL spec. Implement per spec semantics.\nfunc ${fn}(args ...any) ${ret} {\n\tpanic("speckl: domain function not implemented: ${fn}")\n}`;
      }).join('\n\n')
    : '';

  const actionMethods = actions
    .map(a => emitAction(a, nameMap, mapVarOrigNames, goNameS, stateEnumName, knownStateValues, enumMap))
    .join('\n\n');

  const invariantChecks = constraints.map((c, i) => {
    // constraints whose body is comments only are vacuously true
    const cExpr = c.expr.split('\n').map(l => l.replace(/\/\/.*$/, '').trim()).filter(Boolean).join('\n').trim();
    const fname = `Check${goName(c.name || 'Invariant' + i)}`;
    // peel forall prefixes (supports nested forall and .keys/.values suffixes)
    const forallRe = /^forall\s+(\w+)\s+in\s+(\w+)(\.values(?:\(\))?|\.keys(?:\(\))?)?:\s*([\s\S]+)$/;
    const loops: { varName: string; collName: string; mode: 'keys' | 'values' }[] = [];
    let rest = cExpr;
    let fm: RegExpMatchArray | null;
    while ((fm = rest.match(forallRe))) {
      loops.push({ varName: fm[1], collName: fm[2], mode: fm[3] && fm[3].startsWith('.keys') ? 'keys' : 'values' });
      rest = fm[4];
    }
    let body: string;
    if (loops.length > 0) {
      const loopRecords = new Map<string, string>();
      for (const l of loops) {
        const vt = stateVarTypes.get(l.collName);
        if (vt?.type === 'map' && vt.valueType?.type === 'ident') loopRecords.set(l.varName, cleanName(vt.valueType.name));
        if (vt?.type === 'list' && vt.elementType?.type === 'ident') loopRecords.set(l.varName, cleanName(vt.elementType.name));
      }
      const keyVars = new Set(loops.filter(l => l.mode === 'keys').map(l => l.varName));
      const varRef = (v: string) => (keyVars.has(v) ? v : v + 'Val');
      const renameLoopVars = (s2: string) => {
        let out = s2.replace(/\b(\w+)\.(\w+)/g, (m2, obj, f) => {
          const mapped = goFieldRenames.get(f);
          return mapped ? `${obj}.${mapped}` : m2;
        });
        for (const l of loops) {
          // don't rename the machine receiver `m.<stateField>` - only the
          // loop variable's own field accesses
          const stateFields = Array.from(nameMap.values()).join('|');
          out = out.replace(new RegExp(`\\b${escapeRegex(l.varName)}\\b(?!\\.(?:${stateFields})\\b)`, 'g'), varRef(l.varName));
        }
        return out;
      };
      const lines: string[] = [];
      for (let d = 0; d < loops.length; d++) {
        const l = loops[d];
        const vt = stateVarTypes.get(l.collName);
        const gColl = nameMap.get(l.collName) || camelCase(l.collName);
        if (l.mode === 'keys' && vt?.type === 'map') {
          lines.push(`${'\t'.repeat(d + 1)}for ${l.varName} := range m.${gColl} {`);
        } else {
          lines.push(`${'\t'.repeat(d + 1)}for _, ${l.varName}Val := range m.${gColl} {`);
        }
      }
      const depth = loops.length;
      const localNames2 = new Set<string>(loops.map(l => l.varName));
      const bodyLines2: string[] = [];
      let unlowerable = false;
      for (const st of rest.split('\n').map(l2 => l2.trim()).filter(Boolean)) {
        const lm = st.match(/^let\s+(\w+)\s*:=\s*([\s\S]+)$/);
        if (lm) {
          const val = renameLoopVars(goImplications(rewriteGoExpr(lm[2], nameMap, mapVarOrigNames, localNames2, stateEnumName, knownStateValues, loopRecords)));
          const brm = lm[2].trim().match(/^(\w+)\[.+\]$/);
          if (brm) {
            const vt2 = stateVarTypes.get(brm[1]);
            if (vt2?.type === 'map' && vt2.valueType?.type === 'ident') loopRecords.set(lm[1], cleanName(vt2.valueType.name));
          }
          bodyLines2.push(`${'\t'.repeat(depth + 1)}${camelCase(lm[1])} := ${val}`);
          localNames2.add(lm[1]);
        } else {
          const exprGo = renameLoopVars(goImplications(rewriteGoExpr(st, nameMap, mapVarOrigNames, localNames2, stateEnumName, knownStateValues, loopRecords)));
          unlowerable = unlowerable || /\bimplies\(/.test(exprGo) || /\b\w+\s+has\s+\w+\b(?!\()/.test(exprGo);
          bodyLines2.push(`${'\t'.repeat(depth + 1)}if !(${exprGo}) {`);
          bodyLines2.push(`${'\t'.repeat(depth + 2)}return false`);
          bodyLines2.push(`${'\t'.repeat(depth + 1)}}`);
        }
      }
      lines.push(...bodyLines2);
      for (let d = loops.length - 1; d >= 0; d--) lines.push(`${'\t'.repeat(d + 1)}}`);
      if (unlowerable) {
        body = `\t// TODO: manual review - invariant could not be mechanically lowered:\n\t// ${cExpr.replace(/\s+/g, ' ').replace(/\*\//g, '* /')}\n\treturn true`;
      } else {
        lines.push('\treturn true');
        body = lines.join('\n');
      }
    } else {
      if (!cExpr) {
        body = '\treturn true';
      } else {
        body = `\treturn ${goImplications(rewriteGoExpr(cExpr, nameMap, mapVarOrigNames, new Set<string>(), stateEnumName, knownStateValues))}`;
      }
    }
    return `// Invariant ${fname}: ${cExpr.replace(/\s+/g, ' ').slice(0, 90)}\nfunc (m *${structName}) ${fname}() bool {\n${body}\n}`;
  }).join('\n\n');


  const eventLogField = events.length > 0 ? '\n\t// EventLog records every decision (spec events).\n\tEventLog []any' : '';
  const eventStructsBlock = events.length > 0
    ? eventStructs + `\n\n// ${goNameS}Event union marker.\ntype ${goNameS}Event interface{ is${goNameS}Event() }`
    : '';

  const bodyText = [actionMethods, invariantChecks, initBody].join('\n');
  const importNames = ['fmt', 'strings', 'strconv'].filter(i => bodyText.includes(i + '.'));
  if (bodyText.includes('time.')) importNames.push('time');
  const importBlock = importNames.length > 0
    ? 'import (\n' + importNames.map(i => '\t"' + i + '"').join('\n') + '\n)'
    : '';

  return [
    `// Code generated by speckl (go backend) from ${speck.name}.speckdl. DO NOT EDIT BY HAND.`,
    `// Clean-room generated from the SpeckDL specification; contains no third-party code.`,
    `// Domain-function stubs must be implemented per the spec text.`,
    `package ${snakeCase(speck.name)}`,
    '',
    importBlock,
    '',
    enumDefs.join('\n'),
    '',
    recordStructs,
    '',
    eventStructsBlock,
    '',
    `// ${structName} - state machine generated from the SpeckDL specification.`,
    `type ${structName} struct {`,
    `\t${stateFields}${eventLogField}`,
    '}',
    '',
    `// New${goNameS}Machine constructs the machine in its initial state.`,
    `func New${goNameS}Machine() *${structName} {`,
    `\tm := &${structName}{}`,
    initBody.split('\n').map(l => '\t' + l.trim()).join('\n'),
    `\treturn m`,
    '}',
    '',
    actionMethods,
    '',
    invariantChecks,
    ...(stubs ? ['', stubs] : []),
  ].join('\n');
}

// ─── actions ────────────────────────────────────────────────────────

function emitAction(
  action: ActionNode,
  nameMap: Map<string, string>,
  mapVarOrigNames: Set<string>,
  speckName: string,
  stateEnumName: string,
  knownStateValues: string[],
  enumMap: Map<string, string[]>
): string {
  const localNames = new Set(action.params.map(p => cleanName(p.name)));
  const params = action.params
    .map(p => `${camelCase(cleanName(p.name))} ${goType(p.type, speckName, enumMap)}`)
    .join(', ');
  const methodName = goName(action.name);
  const hasReturn = action.statements.some(s => s.type === 'return');
  const nullableParams = new Set(action.params.filter((p: any) => p.type?.nullable).map((p: any) => camelCase(cleanName(p.name))));
  const localRecords = new Map<string, string>();
  for (const p of action.params as any[]) {
    if (p.type?.type === 'ident' && !['Nat','Int','Real','Number','Bool','String','Bytes','Date'].includes(cleanName(p.type.name)) && !currentEnumMap.has(cleanName(p.type.name))) {
      localRecords.set(cleanName(p.name), cleanName(p.type.name));
    }
  }
  const retSig = hasReturn ? '(ret any, err error)' : '(err error)';

  const emitAssign = (s: any): string => {
    const target = String(s.target);
    // nested field assign: mapVar[key].field := val
    const nested = target.match(/^(\w+)\[(.+)\]\.(\w+)$/);
    if (nested) {
      const gname = nameMap.get(cleanName(nested[1])) || camelCase(cleanName(nested[1]));
      const key = rewriteGoExpr(nested[2], nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      const gfield = goFieldRenames.get(nested[3]) || goName(nested[3]);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      let v = val;
      const vt = stateVarTypes.get(cleanName(nested[1]));
      const rec = vt?.type === 'map' && vt.valueType?.type === 'ident' ? cleanName(vt.valueType.name) : undefined;
      const ftype = rec ? recordFieldTypes.get(rec)?.get(nested[3]) : undefined;
      if (ftype?.nullable && /^([A-Za-z_]\w*)$/.test(val) && val !== 'nil' && !nullableParams.has(val)) v = `\u0026${val}`;
      // Go: cannot assign through a map to a struct field — read-modify-write
      return [
        `\t{`,
        `\t\tc := m.${gname}[${key}]`,
        `\t\tc.${gfield} = ${v}`,
        `\t\tm.${gname}[${key}] = c`,
        `\t}`,
      ].join('\n');
    }
    const bracket = target.match(/^(\w+)\[(.+)]$/);
    if (bracket) {
      const gname = nameMap.get(cleanName(bracket[1])) || camelCase(cleanName(bracket[1]));
      const key = rewriteGoExpr(bracket[2], nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      let val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      // inline record literal assigned to a map value: { k: v, ... } -> TypeName{ K: v, ... }
      const vt = stateVarTypes.get(cleanName(bracket[1]));
      if (vt?.type === 'map' && vt.valueType?.type === 'ident') {
        const recName = cleanName(vt.valueType.name);
        const lit = val.match(/^\{\s*([\s\S]*)\s*\}$/);
        if (lit) {
          const inner = lit[1].replace(/(\w+)\s*:/g, (_, f) => `${goName(f)}:`);
          val = `${recName}{ ${inner} }`;
        }
      }
      return `\tm.${gname}[${key}] = ${val}`;
    }
    // local record field assign: localVar.field := val (let-bound local, not a state var)
    const dotted = target.match(/^(\w+)\.(\w+)$/);
    if (dotted && !nameMap.has(cleanName(dotted[1])) && localNames.has(cleanName(dotted[1]))) {
      const gfield = goFieldRenames.get(dotted[2]) || goName(dotted[2]);
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      let v = val;
      const rec = letRecords.get(cleanName(dotted[1]));
      const ftype = rec ? recordFieldTypes.get(rec)?.get(dotted[2]) : undefined;
      if (ftype?.nullable && val !== 'nil') {
        // assigning a non-pointer into a pointer field: take its address
        if (/^([A-Za-z_]\w*)$/.test(val)) {
          if (!currentNullableVars.has(val)) v = `&${val}`;
        } else if (/^\u0000\d+\u0000$/.test(val)) {
          return `\t{ s := ${val}; ${camelCase(cleanName(dotted[1]))}.${gfield} = &s }`;
        } else if (!/[()]$/.test(val)) {
          v = `&${val}`;
        } else {
          return `\t{ s := ${val}; ${camelCase(cleanName(dotted[1]))}.${gfield} = &s }`;
        }
      }
      return `\t${camelCase(cleanName(dotted[1]))}.${gfield} = ${v}`;
    }
    const gname = nameMap.get(cleanName(target)) || camelCase(cleanName(target));
    // let-bound local reassignment: target = val (not a state var)
    if (!nameMap.has(cleanName(target)) && localNames.has(cleanName(target))) {
      const val2 = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      return `\t${camelCase(cleanName(target))} = ${val2}`;
    }
    const rawExpr = String(s.expr);
    // SpeckDL append form: list :: elem  ->  list = append(list, elem)
    // (some specs write the list on the left of ::)
    const app = rawExpr.match(/^(\w+)\s*::\s*([\s\S]+)$/);
    if (app && stateVarTypes.get(cleanName(app[1]))?.type === 'list') {
      const listVar = app[1];
      const gname2 = nameMap.get(cleanName(listVar)) || camelCase(cleanName(listVar));
      const elemType = (stateVarsOf(listVar) || '').replace(/^\[\]/, '');
      const elem = fixRecordLiteral(rewriteGoExpr(app[2].trim(), nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords), elemType);
      return `\tm.${gname2} = append(m.${gname2}, ${elem})`;
    }
    // SpeckDL cons: ELEM :: list  ->  list = append([]Elem{elem}, list)
    const cons = rawExpr.match(/^(.+)\s*::\s*(\w+)$/s);
    if (cons) {
      const listVar = cons[2];
      const gname2 = nameMap.get(cleanName(listVar)) || camelCase(cleanName(listVar));
      const elemType = (stateVarsOf(listVar) || '').replace(/^\[\]/, '');
      const elem = fixRecordLiteral(rewriteGoExpr(cons[1].trim(), nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords), elemType);
      return `\tm.${gname2} = append([]${elemType}{ ${elem} }, m.${gname2}...)`;
    }
    let val = rewriteGoExpr(rawExpr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues);
    // Collection .empty() in an action body: lower via the target's own type
    if (/^(List|Map|Set)\.empty\(\)$/.test(val)) {
      const vt2 = stateVarTypes.get(cleanName(target));
      val = defaultGoValue(vt2, speckName, enumMap);
    }
    // Map { "k" -> v, ... } literal: lower via the target's key/value types
    const vtMap = stateVarTypes.get(cleanName(target));
    const mapLit = lowerMapLiteral(val, vtMap);
    if (mapLit) val = mapLit;
    // Nullable (pointer) state var assigned a plain string value: the value
    // must become a pointer (temp var for literals/calls, & for variables)
    const vt3 = stateVarTypes.get(cleanName(target));
    if (vt3?.nullable && goType({ ...vt3, nullable: false }, speckName, enumMap) === 'string') {
      if (val === 'nil') return `\tm.${gname} = nil`;
      if (/^(time\.Now\(\)\.Unix\(\)|nowString\(\))$/.test(val)) {
        return `\t{ s := nowString(); m.${gname} = &s }`;
      }
      if (/^([A-Za-z_]\w*)$/.test(val)) {
        if (!currentNullableVars.has(val)) return `\tm.${gname} = &${val}`;
      } else if (/^\u0000\d+\u0000$/.test(val) || /[()]$/.test(val)) {
        return `\t{ s := ${val}; m.${gname} = &s }`;
      } else {
        return `\tm.${gname} = &${val}`;
      }
    }
    // Nullable (pointer) state var assigned a record literal: take its address
    if (vt3?.nullable && /^([A-Za-z_]\w*)\s*\{/.test(val)) {
      return `\tm.${gname} = &${val}`;
    }
    return `\tm.${gname} = ${val}`;
  };

  // Lower a brace-form conditional captured by the parser pre-pass:
  //   "if <cond> { <stmts> } [else { <stmts> }]"
  const emitIfBlock = (raw: string): string => {
    const open = raw.indexOf('{');
    if (open < 0) return `\t// TODO: conditional not lowered: ${raw.replace(/\n/g, ' ')}`;
    const cond = raw.slice(3, open).trim().replace(/:\s*$/, '');
    // find the top-level '} else {' (if any) and the final top-level '}'
    let depth = 0, elseSplit = -1, closeIdx = -1;
    for (let i = open; i < raw.length; i++) {
      const ch = raw[i];
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          if (raw.startsWith('} else {', i)) { elseSplit = i; i += '} else {'.length - 1; continue; }
          closeIdx = i; break;
        }
      }
    }
    if (closeIdx < 0) return `\t// TODO: conditional not lowered (unbalanced): ${raw.replace(/\n/g, ' ')}`;
    const thenPart = raw.slice(open + 1, elseSplit >= 0 ? elseSplit : closeIdx);
    const elsePart = elseSplit >= 0 ? raw.slice(elseSplit + '} else {'.length, closeIdx) : null;
    const condGo = goImplications(rewriteGoExpr(cond, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords));
    const emitStmts = (text: string): string[] => {
      const lines: string[] = [];
      for (const st of splitAssignStmts(text)) {
        const letM = st.match(/^let\s+(\w+)\s*:=\s*([\s\S]*)$/);
        if (letM) {
          const nm = cleanName(letM[1]);
          localNames.add(nm);
          const callM = letM[2].trim().match(/^([a-z_]\w*)\s*\(/);
          if (callM && currentFnRetTypes.get(callM[1]) === 'string') currentLetStringVars.add(nm);
          const val = rewriteGoExpr(letM[2].trim(), nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
          if (/^[A-Za-z_]\w*$/.test(val) && currentNullableVars.has(val)) currentNullableVars.add(nm);
          lines.push(`\t${camelCase(nm)} := ${val}`);
          const litM = letM[2].trim().match(/^([A-Za-z_]\w*)\s*\{/);
          if (litM) letRecords.set(nm, cleanName(litM[1]));
          const brM = letM[2].trim().match(/^(\w+)\[([\s\S]+)\]$/);
          if (brM) {
            const vt = stateVarTypes.get(cleanName(brM[1]));
            if (vt?.type === 'map' && vt.valueType?.type === 'ident') letRecords.set(nm, cleanName(vt.valueType.name));
            else if (vt?.type === 'list' && vt.elementType?.type === 'ident') letRecords.set(nm, cleanName(vt.elementType.name));
          }
          continue;
        }
        const am = st.match(/^([\s\S]+?)\s*:=\s*([\s\S]*)$/);
        if (am) { lines.push(emitAssign({ type: 'assign', target: am[1], expr: am[2] } as any)); continue; }
        lines.push(`\t_ = ${st}`);
      }
      return lines;
    };
    const thenLines = emitStmts(thenPart.trim());
    let out = `\tif ${condGo} {\n${thenLines.join('\n') || '\t'}\n\t}`;
    if (elsePart !== null) {
      const elseLines = emitStmts(elsePart.trim());
      out += ` else {\n${elseLines.join('\n') || '\t'}\n\t}`;
    }
    return out;
  };

  // emit statements in source order so lets declared before guards/assigns
  // that reference them are emitted in the correct sequence
  const letRecords = new Map<string, string>();
  const currentLetStringVars = new Set<string>();
  currentLetStringVars.clear();
  currentNullableVars = new Set(nullableParams);
  const bodyLines: string[] = [];
  for (const s of action.statements as any[]) {
    if (s.type === 'require' || s.type === 'precondition') {
      const expr = goImplications(rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords));
      bodyLines.push(`\tif !(${expr}) {\n\t\terr = fmt.Errorf("guard failed: ${String(s.expr).replace(/"/g, "'")}")\n\t\treturn\n\t}`);
    } else if (s.type === 'let') {
      localNames.add(s.name);
      const callM = String(s.expr ?? '').trim().match(/^([a-z_]\w*)\s*\(/);
      if (callM && currentFnRetTypes.get(callM[1]) === 'string') currentLetStringVars.add(cleanName(s.name));
      const val = rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords);
      if (/^[A-Za-z_]\w*$/.test(val) && currentNullableVars.has(val)) currentNullableVars.add(cleanName(s.name));
      const litInt = val.match(/^\d+$/);
      bodyLines.push(`\t${camelCase(s.name)} := ${litInt ? `int64(${val})` : val}`);
      // track the record type of the let-bound local (for nullable field assigns)
      const exprRaw = String(s.expr ?? '');
      const bracketM = exprRaw.match(/^(\w+)\[(.+)\]$/s);
      if (bracketM) {
        const vt = stateVarTypes.get(bracketM[1]);
        if (vt?.type === 'map' && vt.valueType?.type === 'ident') letRecords.set(cleanName(s.name), cleanName(vt.valueType.name));
        else if (vt?.type === 'list' && vt.elementType?.type === 'ident') letRecords.set(cleanName(s.name), cleanName(vt.elementType.name));
      } else {
        const litM = exprRaw.match(/^([A-Za-z_]\w*)\s*\{/);
        if (litM) letRecords.set(cleanName(s.name), cleanName(litM[1]));
      }
    } else if (s.type === 'assign') {
      bodyLines.push(emitAssign(s));
    } else if (s.type === 'ifblock') {
      bodyLines.push(emitIfBlock(String((s as any).raw ?? '')));
    } else if (s.type === 'emit') {
      const fields = ((s.fields ?? []) as any[])
        .map((f: any) => `${goName(f.name)}: ${rewriteGoExpr(f.value, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords)}`)
        .join(', ');
      bodyLines.push(`\tm.EventLog = append(m.EventLog, ${goName(s.event)}{ ${fields} })`);
    } else if (s.type === 'return') {
      bodyLines.push(`\tret = ${rewriteGoExpr(s.expr, nameMap, mapVarOrigNames, localNames, stateEnumName, knownStateValues, localRecords)}`);
    }
  }

  let body = bodyLines.length ? bodyLines.join('\n') : '\treturn';
  body += '\n\treturn';

  return `// Execute action: ${action.name}\nfunc (m *${goName(speckName)}Machine) ${methodName}(${params}) ${retSig} {\n${body}\n}`;
}

// ─── handlers (HTTP + htmx surface) ─────────────────────────────────

function emitHandlers(speck: SpeckNode): string {
  const actions = speck.members.filter(m => m.type === 'action') as ActionNode[];
  const structName = `${goName(speck.name)}Machine`;
  const handlers = actions.map(a => {
    const route = `/actions/${snakeCase(a.name)}`;
    const typedFields = a.params
      .map(p => `\t\t\t${goName(p.name)} ${goType(p.type, speck.name, currentEnumMap)} \`json:"${camelCase(cleanName(p.name))}"\``)
      .join('\n');
    const argNames = a.params.map(p => `req.${goName(p.name)}`).join(', ');
    const hasRet = a.statements.some(s => s.type === 'return');
    const call = hasRet
      ? `ret, err := m.${goName(a.name)}(${argNames})`
      : `err := m.${goName(a.name)}(${argNames})`;
    const resp = hasRet
      ? `\t\tjson.NewEncoder(w).Encode(map[string]any{"ok": true, "result": ret})`
      : `\t\tjson.NewEncoder(w).Encode(map[string]any{"ok": true})`;
    return `	// ${a.name} — POST ${route} (htmx: hx-post="${route}")
	mux.HandleFunc("POST ${route}", auth(func(w http.ResponseWriter, r *http.Request) {
		var req struct {
${typedFields}
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		${call}
		if err != nil {
			json.NewEncoder(w).Encode(map[string]any{"ok": false, "error": err.Error()})
			return
		}
${resp}
		m.Save()
	}));`;
  }).join('\n\n');

  return `// Code generated by speckl (go backend): HTTP + htmx surface.
//
// Frontend model: Go html/template + htmx. Each spec action gets a POST
// endpoint; htmx forms POST to these endpoints and swap fragments with the
// response. Mount with RegisterHandlers(mux, machine).
//
// Auth: set GB_API_KEY to require X-API-Key on every action call.
// Persistence: set GB_STATE_PATH (default ./state.json) — state snapshots
// are written after every successful mutation and loaded at boot.
package ${snakeCase(speck.name)}

import (
	"encoding/json"
	"net/http"
)

func RegisterHandlers(mux *http.ServeMux, m *${structName}) {
${handlers}

	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]any{"status": "ok", "machine": "${goName(speck.name)}"})
	})

	mux.HandleFunc("GET /state.json", auth(func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(m)
	}))
}
`;
}



function emitStore(speck: SpeckNode): string {
  const structName = `${goName(speck.name)}Machine`;
  return `// Code generated by speckl (go backend): JSON snapshot persistence.
package ${snakeCase(speck.name)}

import (
	"encoding/json"
	"net/http"
	"os"
)

// statePath - where the machine snapshot lives (GB_STATE_PATH, default ./state.json).
func statePath() string {
	if p := os.Getenv("GB_STATE_PATH"); p != "" {
		return p
	}
	return "./state.json"
}

// Save writes a full state snapshot (including the event log).
func (m *${structName}) Save() {
	b, err := json.Marshal(m)
	if err != nil {
		return
	}
	os.WriteFile(statePath(), b, 0600)
}

// Load restores a previous state snapshot. Missing file = fresh machine.
func (m *${structName}) Load() {
	b, err := os.ReadFile(statePath())
	if err != nil {
		return
	}
	json.Unmarshal(b, m)
}

// auth - API-key middleware. If GB_API_KEY is unset, requests are allowed
// (single-operator mode). Set GB_API_KEY to lock actions down.
func auth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		key := os.Getenv("GB_API_KEY")
		if key == "" || r.Header.Get("X-API-Key") == key {
			next(w, r)
			return
		}
		http.Error(w, "unauthorized", http.StatusUnauthorized)
	}
}
`;
}



function emitMain(speck: SpeckNode): string {
  const structName = `${goName(speck.name)}Machine`;
  const goNameS = goName(speck.name);
  return `// Code generated by speckl (go backend): deployable service entrypoint.
//
// Env:
//   PORT          listen port (default 8080)
//   GB_API_KEY    if set, actions require X-API-Key header
//   GB_STATE_PATH state file (default ./state.json)
//
// Deploy: ships with a Dockerfile — any container host works (Railway,
// Fly, Compose). Single static binary, SQLite-free by default.
package main

import (
	"log"
	"net/http"
	"os"

	machine "speckl/${snakeCase(speck.name)}"
)

func main() {
	m := machine.New${goNameS}Machine()
	m.Load()

	mux := http.NewServeMux()
	machine.RegisterHandlers(mux, m)

	addr := ":" + orDefault(os.Getenv("PORT"), "8080")
	// compiled UI assets: serve ./static (Elm app.js, css) and ./ui (index.html)
	mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
	mux.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		b, err := os.ReadFile("ui/index.html")
		if err != nil {
			http.Error(w, "UI not found", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write(b)
	})

	log.Printf("speckl ${snakeCase(speck.name)}: listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}

func orDefault(v, d string) string {
	if v == "" {
		return d
	}
	return v
}

var _ = machine.${structName}{}
`;
}


function emitDockerfile(speck: SpeckNode): string {
  const pkg = snakeCase(speck.name);
  return `FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY *.go ./
RUN go build -o /out/server .

FROM alpine:3.20
COPY --from=build /out/server /usr/local/bin/server
ENV PORT=8080 GB_STATE_PATH=/data/state.json
VOLUME /data
EXPOSE 8080
CMD ["/out/server"]
`;
}


// ─── helpers ────────────────────────────────────────────────────────

function memberKey(m: MemberNode): string {
  if (m.type === 'action') return `action:${m.name}`;
  if (m.type === 'event') return `event:${m.name}`;
  if (m.type === 'interface') return `interface:${m.name}`;
  if (m.type === 'state') return 'state';
  if (m.type === 'init') return 'init';
  if (m.type === 'provenance') return 'provenance';
  if (m.type === 'bom') return 'bom';
  if (m.type === 'input') return 'input';
  if (m.type === 'output') return 'output';
  if (m.type === 'verify') return `verify:${(m as any).temporalExpr || ''}`;
  if (m.type === 'constraint') return `constraint:${(m as any).expr || ''}`;
  if (m.type === 'oneof') return `oneof:${(m as any).name || ''}`;
  if (m.type === 'transition') return `transition:${(m as any).name || ''}`;
  if (m.type === 'service') return `service:${(m as any).name || ''}`;
  return m.type;
}

function isEmptyStub(m: MemberNode): boolean {
  if (m.type === 'state') return m.variables.length === 0;
  if (m.type === 'init') return m.assignments.length === 0;
  if (m.type === 'action') return m.statements.length === 0;
  if (m.type === 'event') return m.fields.length === 0;
  if (m.type === 'interface') return m.methods.length === 0;
  if (m.type === 'provenance') return m.clauses.length === 0;
  if (m.type === 'bom') return !m.compiler && !m.solver && !m.runtime;
  return false;
}

function cleanName(s: string): string { return s.replace(/,$/, '').trim(); }
function cleanExpr(s: string): string { return s.replace(/,$/, '').trim(); }
function escapeRegex(s: string): string { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// Split a brace-form branch body into top-level statements. A statement
// starts at each depth-0 `:=` (walking back to the lvalue token start, or
// to a `let` keyword). Record-literal `field:` pairs sit inside braces and
// are never statement boundaries.
function splitAssignStmts(text: string): string[] {
  const starts: number[] = [];
  let depth = 0;
  let inStr = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === '"') inStr = !inStr;
    if (inStr) continue;
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    else if (ch === ':' && depth === 0 && text[i + 1] === '=') {
      let j = i - 1;
      while (j >= 0 && text[j] === ' ') j--;
      while (j >= 0 && /[\w\]\[.]/.test(text[j])) j--;
      const before = text.slice(0, j + 1).trimEnd();
      if (before.endsWith('let')) j = before.length - 3;
      starts.push(j + 1);
    }
  }
  const stmts: string[] = [];
  for (let k = 0; k < starts.length; k++) {
    const end = k + 1 < starts.length ? starts[k + 1] : text.length;
    const st = text.slice(starts[k], end).trim();
    if (st) stmts.push(st);
  }
  return stmts;
}

function goName(s: string): string {
  return s.split(/[^a-zA-Z0-9]+/).filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}
function camelCase(s: string): string {
  const c = goName(s);
  return c.charAt(0).toLowerCase() + c.slice(1);
}
function snakeCase(s: string): string {
  return s.replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .replace(/([a-zA-Z])(\d)/g, '$1_$2')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toLowerCase()
    .replace(/_+/g, '_').replace(/^_|_$/g, '');
}

function defaultGoValue(typeExpr: any, speckName: string = '', enumMap: Map<string, string[]> = new Map()): string {
  if (!typeExpr) return 'nil';
  if (typeExpr.nullable) return 'nil';
  if (typeExpr.type === 'ident' && enumMap?.has(cleanName(typeExpr.name))) {
    const vals = enumMap.get(cleanName(typeExpr.name))!;
    if (vals.length > 0) return `${goName(speckName)}${goName(cleanName(typeExpr.name))}${goName(vals[0])}`;
    return 'nil';
  }
  if (typeExpr.type === 'primitive') {
    switch (typeExpr.name) {
      case 'Nat': case 'Int': case 'Date': return '0';
      case 'Real': case 'Number': return '0.0';
      case 'Bool': return 'false';
      case 'String': return '""';
      default: return 'nil';
    }
  }
  if (typeExpr.type === 'ident') {
    const gn = goName(cleanName(typeExpr.name));
    if (recordTypes.has(gn)) return `${gn}{}`;
  }
  if (typeExpr.type === 'list') return `[]${goType(typeExpr.elementType, '', new Map())}{}`;
  if (typeExpr.type === 'set') return `map[${goType(typeExpr.elementType, '', new Map())}]bool{}`;
  if (typeExpr.type === 'map') return `map[${goType(typeExpr.keyType, '', new Map())}]${goType(typeExpr.valueType, '', new Map())}{}`;
  return 'nil';
}