// graphql.ts — GraphQL schema target.
//
// Consumes the IR's typed_schema + service to emit a GraphQL schema.
// Each record becomes an object type; each enum becomes an enum type;
// each service becomes a Query/Mutation type with one field per RPC.

import * as fs from 'fs';
import * as path from 'path';
import { IR, IRRecordType, IRFieldDef, IRTypeRef, IRSpeck, IREnumType } from '../ir/types.js';

export class GraphQLTarget {
  generate(ir: IR, options: { outputDir: string }): string {
    const outDir = path.join(options.outputDir, 'graphql');
    fs.mkdirSync(outDir, { recursive: true });

    const docs: string[] = [];
    for (const speck of ir.specks) {
      const doc = this.render(speck);
      docs.push(doc);
      const filename = path.join(outDir, `${speck.name.toLowerCase()}.graphql`);
      fs.writeFileSync(filename, doc);
      console.log(`Generated GraphQL schema: ${filename}`);
    }
    return docs.join('\n');
  }

  private render(speck: IRSpeck): string {
    const lines: string[] = [];
    lines.push(`# ${speck.name} GraphQL schema`);
    lines.push(`# Generated by speckl from ${speck.name}.speckdl`);
    lines.push(`# Source provenance: ${speck.facets.provenance.clauses.length} clauses`);
    lines.push('');

    // Enums first (they're referenced by records)
    for (const [name, type] of speck.facets.typed_schema.types.entries()) {
      if (type.kind === 'enum') {
        lines.push(`enum ${name} {`);
        for (const v of (type as IREnumType).variants) {
          lines.push(`  ${v}`);
        }
        lines.push(`}`);
        lines.push('');
      }
    }

    // Records (skip XxxSpec/XxxStatus companions — they're CRD scaffolding,
    // not GraphQL types)
    for (const [name, type] of speck.facets.typed_schema.types.entries()) {
      if (type.kind !== 'record') continue;
      if (name.endsWith('Spec') || name.endsWith('Status')) continue;
      if (name === 'TypeMeta' || name === 'ObjectMeta' || name === 'ListMeta') continue;
      lines.push(this.recordToType(speck, name, type as IRRecordType));
      lines.push('');
    }

    // Services as Query/Mutation root
    for (const service of speck.facets.typed_schema.services) {
      lines.push(`type ${service.name}Query {`);
      for (const method of service.methods) {
        lines.push(`  ${this.methodName(method.name)}(input: ${method.requestType}!): ${method.responseType}!`);
      }
      lines.push(`}`);
      lines.push('');
    }

    return lines.join('\n');
  }

  private recordToType(speck: IRSpeck, name: string, record: IRRecordType): string {
    const lines: string[] = [`type ${name} {`];
    for (const field of record.fields) {
      const optional = field.optional ? '' : '!';
      const gqlType = this.typeRefToGraphQL(speck, field.type, field);
      lines.push(`  ${field.name}: ${gqlType}${optional}`);
    }
    lines.push(`}`);
    return lines.join('\n');
  }

  private typeRefToGraphQL(speck: IRSpeck, typeRef: IRTypeRef, field: IRFieldDef): string {
    if (typeRef.kind === 'primitive') {
      switch (typeRef.primitive) {
        case 'String': return 'String';
        case 'Nat':
        case 'Int': return 'Int';
        case 'Real': return 'Float';
        case 'Bool': return 'Boolean';
        case 'Date': return 'String'; // GraphQL has no native Date
        case 'Bytes': return 'String';
        default: return 'String';
      }
    }
    if (typeRef.kind === 'list' || typeRef.kind === 'set') {
      const inner = this.typeRefToGraphQL(speck, typeRef.elementType!, field);
      return `[${inner}${field.optional ? '' : '!'}]`;
    }
    if (typeRef.kind === 'map') {
      return 'JSON'; // GraphQL has no native map; use scalar
    }
    if (typeRef.kind === 'ident') {
      const namedType = speck.facets.typed_schema.types.get(typeRef.name || '');
      if (namedType?.kind === 'enum') return typeRef.name!;
      return typeRef.name!;
    }
    return 'JSON';
  }

  private methodName(s: string): string {
    // GraphQL convention: camelCase
    return s.charAt(0).toLowerCase() + s.slice(1);
  }
}
