// helm.ts — Helm chart target.
//
// Consumes the IR to emit a basic Helm chart for the CRDs and
// services defined in the spec. Produces Chart.yaml, values.yaml,
// and a templates/ directory with one template per CRD.

import * as fs from 'fs';
import * as path from 'path';
import { IR, IRSpeck, IRRecordType } from '../ir/types.js';

export class HelmTarget {
  generate(ir: IR, options: { outputDir: string }): string {
    for (const speck of ir.specks) {
      const chartDir = path.join(options.outputDir, 'helm', speck.name.toLowerCase());
      fs.mkdirSync(path.join(chartDir, 'templates'), { recursive: true });

      // Chart.yaml
      const chart = {
        apiVersion: 'v2',
        name: speck.name.toLowerCase(),
        version: speck.facets.metadata.version || '0.1.0',
        appVersion: speck.facets.metadata.version || '0.1.0',
        description: this.firstDesignDecision(speck) || `${speck.name} — generated from Speckl`,
        sources: this.provSources(speck),
        keywords: ['speckl', 'kubernetes', 'crd'],
      };
      fs.writeFileSync(
        path.join(chartDir, 'Chart.yaml'),
        JSON.stringify(chart, null, 2)
      );

      // values.yaml
      const values: any = {
        image: {
          repository: speck.name.toLowerCase(),
          tag: speck.facets.metadata.version || 'latest',
        },
        provenance: {
          clauses: speck.facets.provenance.clauses.length,
          authors: speck.facets.provenance.authors.map((a: any) => a.name),
        },
      };
      fs.writeFileSync(
        path.join(chartDir, 'values.yaml'),
        JSON.stringify(values, null, 2)
      );

      // templates/ for each CRD
      const types = speck.facets.typed_schema.types;
      for (const [name, type] of types.entries()) {
        if (type.kind !== 'record') continue;
        if (!types.has(`${name}Spec`) || !types.has(`${name}Status`)) continue;
        const plural = this.pluralize(name.toLowerCase());
        const template = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crdPrefix || "tef.scoble.me" }}/${plural}
spec:
  group: {{ .Values.crdPrefix || "tef.scoble.me" }}
  names:
    kind: ${name}
    listKind: ${name}List
    singular: ${name.toLowerCase()}
    plural: ${plural}
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
`;
        fs.writeFileSync(
          path.join(chartDir, 'templates', `${plural}.crd.yaml`),
          template
        );
      }

      // NOTES.txt
      fs.writeFileSync(
        path.join(chartDir, 'templates', 'NOTES.txt'),
        `Thanks for installing {{ .Chart.Name }} v{{ .Chart.Version }}!

Generated by speckl from ${speck.name}.speckdl
Provenance: ${speck.facets.provenance.clauses.length} clauses
CRDs: ${this.countCRDs(speck)} types
`
      );

      console.log(`Generated Helm chart: ${chartDir}`);
    }
    return '';
  }

  private countCRDs(speck: IRSpeck): number {
    const types = speck.facets.typed_schema.types;
    let count = 0;
    for (const [name, type] of types.entries()) {
      if (type.kind === 'record' && types.has(`${name}Spec`) && types.has(`${name}Status`)) {
        count++;
      }
    }
    return count;
  }

  private firstDesignDecision(speck: IRSpeck): string | undefined {
    const dd = speck.facets.provenance.clauses
      .find((c: any) => c.kind === 'design_decision' || c.type === 'design_decision');
    return dd ? (dd as any).value : undefined;
  }

  private provSources(speck: IRSpeck): string[] {
    return speck.facets.provenance.clauses
      .filter((c: any) => (c.kind || c.type) === 'external_doc' && c.location)
      .map((c: any) => c.location);
  }

  private pluralize(s: string): string {
    if (s.endsWith('s') || s.endsWith('x') || s.endsWith('ch') || s.endsWith('sh')) return s + 'es';
    if (s.endsWith('y') && s.length > 1 && !'aeiou'.includes(s[s.length - 2])) return s.slice(0, -1) + 'ies';
    return s + 's';
  }
}
