// sql.ts — SQL DDL target (PostgreSQL).
//
// Consumes the IR's typed_schema to emit CREATE TABLE statements.
// Records become tables; enums become native PG enums; references
// to other records become foreign keys (best-effort, by name).

import * as fs from 'fs';
import * as path from 'path';
import { IR, IRRecordType, IRFieldDef, IRTypeRef, IRSpeck, IREnumType } from '../ir/types.js';

export class SQLTarget {
  generate(ir: IR, options: { outputDir: string }): string {
    const outDir = path.join(options.outputDir, 'sql');
    fs.mkdirSync(outDir, { recursive: true });

    const docs: string[] = [];
    for (const speck of ir.specks) {
      const doc = this.render(speck);
      docs.push(doc);
      const filename = path.join(outDir, `${speck.name.toLowerCase()}.sql`);
      fs.writeFileSync(filename, doc);
      console.log(`Generated SQL DDL: ${filename}`);
    }
    return docs.join('\n');
  }

  private render(speck: IRSpeck): string {
    const lines: string[] = [];
    lines.push(`-- ${speck.name} PostgreSQL DDL`);
    lines.push(`-- Generated by speckl from ${speck.name}.speckdl`);
    lines.push(`-- ${speck.facets.provenance.clauses.length} provenance clauses`);
    lines.push('');

    // Enums first
    for (const [name, type] of speck.facets.typed_schema.types.entries()) {
      if (type.kind === 'enum') {
        const variants = (type as IREnumType).variants.map((v) => `'${v}'`).join(', ');
        lines.push(`CREATE TYPE ${name.toLowerCase()} AS ENUM (${variants});`);
      }
    }
    lines.push('');

    // Tables
    for (const [name, type] of speck.facets.typed_schema.types.entries()) {
      if (type.kind !== 'record') continue;
      if (name === 'TypeMeta' || name === 'ObjectMeta' || name === 'ListMeta') continue;
      lines.push(this.recordToTable(speck, name, type as IRRecordType));
      lines.push('');
    }

    return lines.join('\n');
  }

  private recordToTable(speck: IRSpeck, name: string, record: IRRecordType): string {
    const tableName = this.toSnakeCase(name);
    const cols: string[] = [];
    let hasPrimaryKey = false;

    for (const field of record.fields) {
      if (field.name === 'id' && !hasPrimaryKey) {
        cols.push(`  ${this.toSnakeCase(field.name)} TEXT PRIMARY KEY`);
        hasPrimaryKey = true;
        continue;
      }
      const sqlType = this.typeRefToSQL(speck, field.type, field);
      const nullability = field.optional ? '' : ' NOT NULL';
      const fk = this.foreignKey(speck, field);
      cols.push(`  ${this.toSnakeCase(field.name)} ${sqlType}${nullability}${fk}`);
    }
    if (!hasPrimaryKey) {
      cols.unshift(`  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()`);
    }
    return `CREATE TABLE ${tableName} (\n${cols.join(',\n')}\n);`;
  }

  private typeRefToSQL(speck: IRSpeck, typeRef: IRTypeRef, field: IRFieldDef): string {
    if (typeRef.kind === 'primitive') {
      switch (typeRef.primitive) {
        case 'String': return 'TEXT';
        case 'Nat':
        case 'Int': return 'BIGINT';
        case 'Real': return 'DOUBLE PRECISION';
        case 'Bool': return 'BOOLEAN';
        case 'Date': return 'TIMESTAMPTZ';
        case 'Bytes': return 'BYTEA';
        default: return 'TEXT';
      }
    }
    if (typeRef.kind === 'list' || typeRef.kind === 'set') {
      const inner = this.typeRefToSQL(speck, typeRef.elementType!, field);
      return `${inner}[]`;
    }
    if (typeRef.kind === 'map') {
      return 'JSONB';
    }
    if (typeRef.kind === 'ident') {
      const namedType = speck.facets.typed_schema.types.get(typeRef.name || '');
      if (namedType?.kind === 'enum') return typeRef.name!.toLowerCase();
      if (namedType?.kind === 'record') {
        return 'TEXT'; // FK reference; would be a UUID in practice
      }
    }
    return 'TEXT';
  }

  private foreignKey(speck: IRSpeck, field: IRFieldDef): string {
    // Heuristic: fields ending in "Id" that reference a known record type
    if (!field.name.endsWith('Id') || field.name === 'id') return '';
    const refName = field.name.slice(0, -2);
    if (speck.facets.typed_schema.types.has(refName)) {
      return ` REFERENCES ${this.toSnakeCase(refName)}(id)`;
    }
    return '';
  }

  private toSnakeCase(s: string): string {
    return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }
}
