// src/generators/typescript-from-ir.ts
//
// Parallel implementation of the TypeScript state machine generator that
// consumes the IR (not the AST). Exists to prove the IR is lossless:
// for any spec, the IR-driven output should match the AST-driven output.
//
// Strategy: read the same SpeckNode data through IR faceted accessors,
// produce the same .ts file. If output diverges, the IR is missing
// something the AST had. If output matches, the IR is verified.
//
// This is the bridge between "the IR exists" and "the IR is the pipeline."

import { IR, IRSpeck, IRStateVar, IRAction, IREvent, IRFieldDef, IRTypeRef } from '../ir/types.js';
import { lower } from '../ir/lower.js';
import { parseSpeckFile } from '../parser.js';
import fs from 'fs';
import path from 'path';

/**
 * Generate TypeScript state machine runtime from a SpeckDL spec, via the IR.
 *
 * @param ir The lowered IR for the spec.
 * @param outputDir Where to write the generated .ts file.
 */
export function generateTypeScriptFromIR(ir: IR, outputDir: string): void {
  for (const speck of ir.specks) {
    const code = emitSpeck(speck);
    const filename = `${speck.name}.ts`;
    const filepath = path.join(outputDir, filename);
    fs.writeFileSync(filepath, code);
    console.log(`Generated TypeScript state machine (from IR): ${filepath}`);
  }
}

/**
 * Convenience: parse a file, lower to IR, generate.
 */
export function generateTypeScriptFromIRFile(filePath: string, outputDir: string): void {
  const ast = parseSpeckFile(filePath);
  const ir = lower(ast, { filePath, resolveImports: false });
  generateTypeScriptFromIR(ir, outputDir);
}

function emitSpeck(speck: IRSpeck): string {
  const { behavior, typed_schema } = speck.facets;

  // Collect enum-like state values from the state vars' types.
  // In the AST version, this required a heuristic (scanning guard expressions
  // for capitalized words). In the IR, we can do better: state values
  // come from the typed_schema's enum types that the state var's type points to.
  const stateValues = collectStateValues(behavior.stateVars, typed_schema.types);

  // Build a state-enum-name resolution like the AST version did.
  const stateEnumName = `${speck.name}State`;

  // Render the TypeScript code.
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by Speckl compiler v0.3 (IR-driven)`);
  lines.push(` * Source: ${speck.sourcePath}`);
  lines.push(` * Provenance: ${speck.facets.provenance.synthesized ? 'synthesized from file metadata' : 'declared in source'}`);
  lines.push(` */`);
  lines.push('');
  lines.push(`// State enum`);
  lines.push(`export const enum ${stateEnumName} {`);
  for (const v of stateValues) {
    lines.push(`  ${v} = '${v}',`);
  }
  lines.push(`}`);
  lines.push('');

  // Event types.
  if (behavior.events.length > 0) {
    lines.push('// Event interfaces');
    for (const ev of behavior.events) {
      lines.push(`export interface ${ev.name} {`);
      for (const f of ev.fields) {
        const optional = f.optional ? '?' : '';
        lines.push(`  ${f.name}${optional}: ${tsType(f.type)};`);
      }
      lines.push(`}`);
      lines.push('');
    }
  }

  // Action methods.
  lines.push('// State machine class');
  lines.push(`export class ${speck.name} {`);
  lines.push(`  private state: ${stateEnumName} = ${stateEnumName}.${stateValues[0] || 'Open'};`);
  lines.push(`  private events: any[] = [];`);
  lines.push('');

  for (const action of behavior.actions) {
    const params = action.params.map(p => `${p.name}: ${tsType(p.type)}`).join(', ');
    lines.push(`  ${action.name}(${params}): void {`);
    // Render each statement (best-effort, since the IR may not capture every
    // expression form yet — we synthesize a stub when we don't know how).
    for (const stmt of action.statements) {
      lines.push(`    ${renderStmt(stmt, '    ')}`);
    }
    lines.push(`  }`);
    lines.push('');
  }

  lines.push('  getState(): ' + stateEnumName + ' { return this.state; }');
  lines.push('  getEvents(): any[] { return this.events; }');
  lines.push('}');

  return lines.join('\n');
}

function collectStateValues(stateVars: IRStateVar[], types: Map<string, any>): string[] {
  if (stateVars.length === 0) return ['Open', 'Closed'];
  const first = stateVars[0];
  if (first.type.kind === 'ident' && first.type.name) {
    const enumType = types.get(first.type.name);
    if (enumType && enumType.kind === 'enum') {
      return enumType.variants;
    }
  }
  // Fall back to Open/Closed like the AST version does.
  return ['Open', 'Closed'];
}

function tsType(t: IRTypeRef): string {
  if (t.kind === 'primitive') {
    switch (t.primitive) {
      case 'String': return 'string';
      case 'Nat':
      case 'Int': return 'number';
      case 'Real': return 'number';
      case 'Bool': return 'boolean';
      case 'Bytes': return 'Uint8Array';
      case 'Date': return 'Date';
      default: return 'any';
    }
  }
  if (t.kind === 'list') return `${tsType(t.elementType!)}[]`;
  if (t.kind === 'set') return `Set<${tsType(t.elementType!)}>`;
  if (t.kind === 'map') return `Map<${tsType(t.keyType!)}, ${tsType(t.valueType!)}>`;
  if (t.kind === 'ident') return t.name || 'any';
  return 'any';
}

function renderStmt(stmt: any, indent: string): string {
  switch (stmt.kind) {
    case 'assign':
      return `this.${stmt.target} = ${renderExpr(stmt.value)};`;
    case 'let':
      return `const ${stmt.letName} = ${renderExpr(stmt.value)};`;
    case 'require':
      return `if (!(${renderExpr(stmt.value)})) throw new Error('require failed');`;
    case 'precondition':
      return `// precondition: ${renderExpr(stmt.value)}`;
    case 'postcondition':
      return `// postcondition: ${renderExpr(stmt.value)}`;
    case 'emit':
      return `this.events.push({ type: '${stmt.event}', ${(stmt.fields || []).map((f: any) => `${f.name}: ${renderExpr(f.value)}`).join(', ')} });`;
    case 'return':
      return `return ${renderExpr(stmt.expr)};`;
    case 'if':
      return `// if-block (not yet lowered): ${stmt.expr ? renderExpr(stmt.expr) : '...'}`;
    default:
      return `// unknown statement kind: ${stmt.kind}`;
  }
}

function renderExpr(e: any): string {
  if (!e) return 'undefined';
  switch (e.kind) {
    case 'bool_lit': return String(e.value);
    case 'int_lit': return String(e.value);
    case 'float_lit': return String(e.value);
    case 'string_lit': return JSON.stringify(e.value);
    case 'ident': return e.name;
    case 'field': return `${renderExpr(e.target)}.${e.field}`;
    case 'index': return `${renderExpr(e.target)}[${renderExpr(e.index)}]`;
    case 'binop': return `(${renderExpr(e.left)} ${e.op} ${renderExpr(e.right)})`;
    case 'unop': return `(${e.op}${renderExpr(e.operand)})`;
    case 'call': return `${e.fn}(${e.args.map(renderExpr).join(', ')})`;
    default: return `/* unhandled expr kind: ${e.kind} */`;
  }
}
