import {
  AST, SpeckNode, MemberNode, StateNode, InitNode, ActionNode,
  ConstraintNode, VerifyNode, TypeExpr, StateVar, ActionStatement
} from '../parser.js';
import fs from 'fs';
import path from 'path';

/**
 * Z3 SMT-LIB2 backend for SpeckDL.
 *
 * Translates SpeckDL invariants, state machines, and verify blocks
 * into SMT-LIB2 for bounded model checking with Z3.
 *
 * Architecture:
 *  - State variables → Z3 sort declarations and const declarations
 *  - invariants → Z3 define-fun returning Bool
 *  - Actions → Z3 define-fun transition predicates (pre → post)
 *  - verify blocks → BMC unrolling with N copies of state
 */

export interface Z3Options {
  verifyDepth: number;
}

const DEFAULT_OPTIONS: Z3Options = {
  verifyDepth: 10,
};

/**
 * InvariantNode — parsed invariant block
 * Parsed directly in the generator from raw block content
 * since the AST parser doesn't yet parse invariants.
 */
export interface InvariantNode {
  type: 'invariant';
  name: string;
  statements: InvariantStatement[];
}

export type InvariantStatement =
  | { type: 'require'; expr: string }
  | { type: 'forall'; var: string; domain: string; expr: string }
  | { type: 'forall_complex'; vars: string[]; domains: string[]; expr: string };

export interface NextNode {
  type: 'next';
  actions: string[]; // action names separated by |
}

/**
 * Generate Z3 SMT-LIB2 from a SpeckDL AST.
 */
export function generateZ3(ast: AST, outputDir: string, options: Z3Options = DEFAULT_OPTIONS): void {
  for (const speck of ast.specks) {
    const code = emitZ3(speck, options);
    const filename = `${speck.name}.smt2`;
    const filepath = path.join(outputDir, filename);
    fs.writeFileSync(filepath, code);
    console.log(`Generated Z3 SMT-LIB2: ${filepath}`);
  }
}

function emitZ3(speck: SpeckNode, options: Z3Options): string {
  const members = speck.members;

  const stateNode = members.find(m => m.type === 'state') as StateNode | undefined;
  const initNode = members.find(m => m.type === 'init') as InitNode | undefined;
  const actions = members.filter(m => m.type === 'action') as ActionNode[];
  const constraints = members.filter(m => m.type === 'constraint') as ConstraintNode[];
  const verifies = members.filter(m => m.type === 'verify') as VerifyNode[];

  // Parse invariants from the raw speck body (handled by parseInvariantsFromSource)
  // Also extract invariants from parsed constraint nodes
  const invariants = extractInvariantsFromConstraints(constraints);
  const sourceInvariants = (speck as any)._invariants || [];
  const allInvariants = [...sourceInvariants, ...invariants];
  
  // Parse next: transition relation
  const nextNode = (speck as any)._next || parseNext(speck);

  const lines: string[] = [];

  // Header
  lines.push(`; SpeckDL: ${speck.name} — Z3 Verification`);
  lines.push(`; Generated by speckl-compile Z3 backend`);
  lines.push(`; Bounded model checking depth: ${options.verifyDepth}`);
  lines.push('');
  lines.push('(set-logic ALL)');
  lines.push('(set-option :produce-models true)');

  // Declare Speckl helper functions
  // speckl_len: length of Array-simulated sequences
  lines.push('(declare-fun speckl_len_Int ( (Array Int Int) ) Int)');
  // speckl_nil: sentinel for nil/null comparisons (SpeckDL nil → Z3 constant)
  lines.push('(declare-const speckl_nil Int)');

  // Step 1: Declare sorts for record types
  const recordTypes = collectRecordTypes(stateNode, actions);
  for (const [name, fields] of recordTypes) {
    emitRecordSort(lines, name, fields);
  }

  // Step 2: Declare state variables as constants
  lines.push('');
  lines.push('; --- State Variables ---');
  const stateVars = stateNode?.variables ?? [];
  const allTypeRefs: string[] = [];

  for (const v of stateVars) {
    emitStateVar(lines, v, allTypeRefs);
  }

  // Declare _post state variables for invariants that compare pre/post state
  // (e.g. "currentTerm' >= currentTerm" → "currentTerm_post >= currentTerm")
  const needsPostVars = allInvariants.some((inv: InvariantNode) =>
    inv.statements.some((s: InvariantStatement) => s.type === 'require' && s.expr.includes("'")));
  if (needsPostVars) {
    for (const v of stateVars) {
      const sort = z3Sort(v.typeExpr);
      lines.push(`(declare-const ${v.name}_post ${sort})`);
    }
  }

  // Step 3: Emit invariants as define-fun
  if (allInvariants.length > 0) {
    lines.push('');
    lines.push('; --- Invariants ---');
    for (const inv of allInvariants) {
      emitInvariant(lines, inv, stateVars);
    }
  }

  // Step 4: Emit constraints as assertions (invariant-based constraints)
  // Constraint invariants are handled via invariant define-fun above
  // plus the BMC unrolling below for verify blocks.
  // For non-verify specs, emit assertion of each invariant:
  if (verifies.length === 0 && allInvariants.length > 0) {
    lines.push('');
    lines.push('; --- Invariant Assertions ---');
    for (const inv of allInvariants) {
      lines.push(`(assert (${inv.name}))`);
    }
  }

  // Step 5: Emit action transition predicates (only for BMC with verify blocks)
  if (verifies.length > 0 && actions.length > 0) {
    lines.push('');
    lines.push('; --- Action Transition Predicates ---');
    for (const action of actions) {
      emitActionTransition(lines, action, stateVars);
    }

    // Step 6: Emit transition relation (next: A | B | C ...)
    if (nextNode && nextNode.actions.length > 0) {
      emitNextTransition(lines, speck.name, nextNode, actions, stateVars);
    }
  }

  // Step 7: Emit bounded model checking for verify blocks
  if (verifies.length > 0 && actions.length > 0) {
    lines.push('');
    lines.push('; --- Bounded Model Checking ---');
    for (const v of verifies) {
      emitBMC(lines, speck.name, v, allInvariants, actions, nextNode, stateVars, options);
    }
  }

  // Step 8: Check-sat and get-model (for simple assertions)
  if (verifies.length === 0) {
    lines.push('');
    lines.push('(check-sat)');
    lines.push('(get-model)');
  }

  return lines.join('\n') + '\n';
}

// --- Type / sort helpers ---

function collectRecordTypes(stateNode: StateNode | undefined, actions: ActionNode[]): Map<string, Map<string, string>> {
  const records = new Map<string, Map<string, string>>();

  // Collect from state variables
  if (stateNode) {
    for (const v of stateNode.variables) {
      collectRecordTypeRefs(v.typeExpr, records);
    }
  }

  // Collect from action params
  for (const a of actions) {
    for (const p of a.params) {
      collectRecordTypeRefs(p.type, records);
    }
  }

  return records;
}

function collectRecordTypeRefs(t: TypeExpr, records: Map<string, Map<string, string>>): void {
  if (t.type === 'record' && t.fields) {
    // Use the record structure — assign a name based on fields for uniqueness
    const key = recordTypeKey(t);
    if (!records.has(key)) {
      const fields = new Map<string, string>();
      for (const f of t.fields) {
        fields.set(f.name, z3Sort(f.type));
      }
      records.set(key, fields);
    }
  } else if (t.type === 'map') {
    if (t.keyType) collectRecordTypeRefs(t.keyType, records);
    if (t.valueType) collectRecordTypeRefs(t.valueType, records);
  } else if (t.type === 'set' || t.type === 'list') {
    if (t.elementType) collectRecordTypeRefs(t.elementType, records);
  } else if (t.type === 'ident') {
    // For named record types (like Account, Transfer, etc.), we declare them as opaque sorts
    const name = t.name || 'Unknown';
    if (!isPrimitive(name) && !isBuiltinType(name)) {
      const key = `ident:${name}`;
      if (!records.has(key)) {
        records.set(key, new Map()); // empty = opaque sort
      }
    }
  }
}

function recordTypeKey(t: TypeExpr): string {
  if (t.type === 'ident' && t.name) {
    return `ident:${t.name}`;
  }
  if (t.fields) {
    const fields = t.fields.map(f => `${f.name}:${z3Sort(f.type)}`).sort().join(',');
    return `record:${fields}`;
  }
  return 'record:unknown';
}

function isPrimitive(name: string): boolean {
  return ['Nat', 'Int', 'Real', 'Bool', 'String', 'Bytes'].includes(name);
}

function isBuiltinType(name: string): boolean {
  return ['List', 'Set', 'Map', 'Array'].some(t => name.startsWith(t));
}

function z3Sort(t: TypeExpr): string {
  if (!t) return 'Int';

  if (t.type === 'primitive') {
    switch (t.name) {
      case 'Nat': return 'Int';
      case 'Int': return 'Int';
      case 'Real': return 'Real';
      case 'Bool': return 'Bool';
      case 'String': return 'String';
      case 'Bytes': return 'String'; // Bytes as String for simplicity
      default: return 'Int';
    }
  }

  if (t.type === 'list') {
    // Lists are modeled as Arrays from Int index to element type
    const elemSort = z3Sort(t.elementType!);
    return `(Array Int ${elemSort})`;
  }

  if (t.type === 'set') {
    // Sets are modeled as (Array T Bool) — membership is select
    const elemSort = z3Sort(t.elementType!);
    return `(Array ${elemSort} Bool)`;
  }

  if (t.type === 'map') {
    const keySort = z3Sort(t.keyType!);
    const valSort = z3Sort(t.valueType!);
    return `(Array ${keySort} ${valSort})`;
  }

  if (t.type === 'record') {
    return recordSortName(t);
  }

  if (t.type === 'ident' && t.name) {
    // Strip ident: prefix, remove Z3-invalid chars, return clean sort name
    let clean = t.name.startsWith('ident:') ? t.name.substring(6) : t.name;
    // Remove parenthesized parameters: Option(NodeId) → Option_NodeId
    clean = clean.replace(/\(([^)]+)\)/g, '_$1').replace(/[<>,\s|"\/]+/g, '_').replace(/__+/g, '_');
    return clean; // Named sort (declared as opaque)
  }

  return 'Int';
}

function recordSortName(t: TypeExpr): string {
  if (t.type === 'ident' && t.name) return t.name;
  if (t.fields) {
    const key = t.fields.map(f => `${f.name}_${z3Sort(f.type)}`).join('_');
    return `Record${simpleHash(key)}`;
  }
  return 'Unknown';
}

function simpleHash(s: string): string {
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = ((hash << 5) - hash) + s.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash).toString(16);
}

function emitRecordSort(lines: string[], name: string, fields: Map<string, string>): void {
  // Sanitize: strip ident: prefix and remove Z3-invalid characters
  let cleanName = name.startsWith('ident:') ? name.substring(6) : name;
  cleanName = cleanName.replace(/\(([^)]+)\)/g, '_$1').replace(/[<>,\s|"/]+/g, '_').replace(/__+/g, '_');

  if (fields.size === 0) {
    // Opaque sort (for named types like Account, Transfer)
    lines.push(`(declare-sort ${cleanName} 0)`);
    return;
  }

  // Declare as a datatype
  lines.push(`(declare-datatypes (( ${cleanName} 0)) ((`);
  lines.push(`  (mk-${cleanName}`);

  for (const [field, sort] of fields) {
    lines.push(`    (${field} ${sort})`);
  }
  lines.push('  )');
  lines.push(')))');
}

// --- State variable emission ---

function emitStateVar(lines: string[], v: StateVar, _allTypeRefs: string[]): void {
  const sort = z3Sort(v.typeExpr);
  const comment = v.defaultInit ? ` ; default: ${v.defaultInit}` : '';
  lines.push(`(declare-const ${v.name} ${sort})${comment}`);
}

// --- Invariant emission ---

function emitInvariant(lines: string[], inv: InvariantNode, stateVars: StateVar[]): void {
  lines.push(`(define-fun ${inv.name} () Bool`);
  lines.push('  (and');

  for (const stmt of inv.statements) {
    if (stmt.type === 'require') {
      // Check if this is a warning comment (English-language constraint skip)
      if (stmt.expr.startsWith('; WARNING:')) {
        lines.push(`    ${stmt.expr}`);
        continue;
      }
      const z3Expr = translateExpr(stmt.expr, stateVars, '');
      lines.push(`    ${z3Expr}`);
    } else if (stmt.type === 'forall') {
      // forall var in domain: expr
      const domainSort = inferDomainSort(stmt.domain, stateVars);
      const z3Expr = translateExpr(stmt.expr, stateVars, '');
      // Replace the bound variable references
      const boundExpr = z3Expr; // var already appears in expr text
      lines.push(`    (forall ((${stmt.var} ${domainSort})) ${boundExpr})`);
    } else if (stmt.type === 'forall_complex') {
      // forall var1, var2, ... in domain1, domain2: expr
      const bindings = stmt.vars.map((v, i) => {
        const sort = inferDomainSort(stmt.domains[i], stateVars);
        return `(${v} ${sort})`;
      }).join(' ');
      const z3Expr = translateExpr(stmt.expr, stateVars, '');
      lines.push(`    (forall (${bindings}) ${z3Expr})`);
    }
  }

  lines.push('  )');
  lines.push(')');
}

function inferDomainSort(domain: string, stateVars: StateVar[]): string {
  // domain might be "accounts.values" or "transfers.keys" or "pending"
  // Match against state variables to infer sort
  const baseVar = domain.split('.')[0];
  const sv = stateVars.find(v => v.name === baseVar);
  if (sv) {
    if (domain.endsWith('.values') && sv.typeExpr.type === 'map') {
      return z3Sort(sv.typeExpr.valueType!);
    }
    if (domain.endsWith('.keys') && sv.typeExpr.type === 'map') {
      return z3Sort(sv.typeExpr.keyType!);
    }
    if (sv.typeExpr.type === 'set') {
      return z3Sort(sv.typeExpr.elementType!);
    }
    if (sv.typeExpr.type === 'list') {
      return z3Sort(sv.typeExpr.elementType!);
    }
    // Handle ident types that are known collection aliases.
    // StringList → element sort String; NatList → Int; etc.
    if (sv.typeExpr.type === 'ident' && sv.typeExpr.name) {
      const typeName = sv.typeExpr.name;
      if (typeName === 'StringList') return 'String';
      if (typeName === 'NatList' || typeName === 'IntList') return 'Int';
      if (typeName === 'BoolList') return 'Bool';
      // Generic pattern: XxxList → Xxx (if Xxx is a primitive)
      const listMatch = typeName.match(/^(\w+)List$/);
      if (listMatch) {
        const elem = listMatch[1];
        if (['Nat', 'Int', 'Real', 'Bool', 'String', 'Bytes'].includes(elem)) {
          return z3Sort({ type: 'primitive', name: elem });
        }
      }
      // For map types accessed via .values or .keys, try the ident name
      if (domain.endsWith('.values')) {
        // Can't infer value type from opaque ident — return Int as fallback
        return 'Int';
      }
    }
  }
  return 'Int'; // fallback
}

// --- Expression translation ---

function translateExpr(expr: string, stateVars: StateVar[], suffix: string): string {
  if (!expr) return 'true';
  let e = expr.trim();

  const stateVarNames = new Set(stateVars.map(v => v.name));
  const reservedWords = new Set([
    'and', 'or', 'not', 'forall', 'exists', 'implies', 'iff',
    'true', 'false', 'in', 'union', 'distinct',
    'now', 'len', 'join', 'old', 'Not', 'Select', 'Set', 'Map',
    'emptySet', 'emptyMap', 'mapKeys', 'values', 'keys',
    'let', 'if', 'then', 'else', 'return', 'require', 'precondition', 'postcondition'
  ]);

  // Protect string literals
  const strings: string[] = [];
  e = e.replace(/"[^"]*"/g, (m) => {
    strings.push(m);
    return `__STR_${strings.length - 1}__`;
  });

  // Handle old() wrapper — spec-level, keep inner
  e = e.replace(/old\(([^()]*(?:\([^()]*\)[^()]*)*)\)/g, '$1');

  // Handle SpeckDL forall: forall r in [0..4]: expr => (forall ((r Int)) expr)
  // Domain [0..4] is a range — for now, treat as Int
  const forallMatch = e.match(/^forall\s+(\w+)\s+in\s+(\[?[\w.\d\-]+\]?):\s*(.+)$/s);
  if (forallMatch) {
    const varName = forallMatch[1];
    const domainSort = inferDomainSort(forallMatch[2], stateVars);
    const bodyExpr = forallMatch[3].trim();
    const bodyZ3 = translateExpr(bodyExpr, stateVars, suffix);
    return `(forall ((${varName} ${domainSort})) ${bodyZ3})`;
  }

  // Handle SpeckDL exists: exists r in collection: expr => (exists ((r Sort)) expr)
  const existsMatch = e.match(/^exists\s+(\w+)\s+in\s+(\[?[\w.\d\-]+\]?):\s*(.+)$/s);
  if (existsMatch) {
    const varName = existsMatch[1];
    const domainSort = inferDomainSort(existsMatch[2], stateVars);
    const bodyExpr = existsMatch[3].trim();
    const bodyZ3 = translateExpr(bodyExpr, stateVars, suffix);
    return `(exists ((${varName} ${domainSort})) ${bodyZ3})`;
  }

  // Handle prime notation for post-state: currentTerm' → currentTerm_post (invariant comparison)
  e = e.replace(/\b(\w+)'/g, '$1_post');

  // Handle implies(x, y) function call pattern — preserve both arguments
  // Use balanced-paren matching to handle nested expressions like
  // implies(branch_id > 0, exists b in branches: b.branch_id == branch_id)
  e = replaceImpliesCall(e);

  // Handle bare implies keyword: implies A B → (=> A B)
  e = e.replace(/\bimplies\s+([^\s]+)\s+(.+)$/g, '(=> $1 $2)');

  // Handle -> as implication (after field access cleanup to avoid false matches)// Handle -> as implication (after field access cleanup to avoid false matches)
  e = e.replace(/->/g, '=>');

  // Handle function calls: length(expr), len(expr), min(a,b), etc.
  e = e.replace(/\blength\(([^)]+)\)/g, 'len__$1__xx');  // marker, fix later
  e = e.replace(/\blen\(([^)]+)\)/g, 'len__$1__xx');  // marker, fix later
  e = e.replace(/\bmin\(([^,)]+),\s*([^)]+)\)/g, 'min__$1__$2__xx');

  // Field access: a.b.c → a_b_c (flatten all dot levels in one pass)
  // For record fields accessed via dot, translate to Z3-safe compound names.
  // Multi-level: m.price.amount → m_price_amount
  e = e.replace(/(\w+)\.(\w+)(\.(\w+))*/g, (match, obj, field1, rest, field2) => {
    if (rest) {
      // Multi-level: m.price.amount → m_price_amount
      return `${obj}_${field1}_${field2}`;
    }
    return `${obj}_${field1}`;
  });

  // Handle nil → Z3 doesn't have nil/null. Translate to a sentinel:
  // x != nil → (distinct x nil_sentinel) — but for Z3 we'll use a special value.
  // For record types (opaque sorts), nil means "no value". We'll use a declared
  // constant `nil` of a generic sort. For Int fields, nil = -1 sentinel.
  // Simplest approach: translate nil to a Z3 declared constant `speckl_nil`.
  e = e.replace(/\bnil\b/g, 'speckl_nil');
  e = e.replace(/\bnull\b/g, 'speckl_nil');

  // Handle notIn BEFORE general patterns
  e = e.replace(/(\S+)\s+notIn\s+(\S+)\.keys/g, '(not (select $2 $1))');

  // Handle x in {val1, val2} BEFORE general 'in' pattern
  e = e.replace(/(\S+)\s+in\s+\{([^}]+)\}/g, (_, x, values) => {
    const vals = values.split(',').map((v: string) => v.trim());
    if (vals.length <= 1) return `(= ${x} ${vals[0] || 'true'})`;
    const clauses = vals.map((v: string) => `(= ${x} ${v})`).join(' ');
    return `(or ${clauses})`;
  });

  // Handle set union
  e = e.replace(/(\S+)\s+union\s+\{([^}]+)\}/g, '(store $1 $2 true)');

  // Handle set difference
  e = e.replace(/(\S+)\s+\\\\\s+\{([^}]+)\}/g, '(store $1 $2 false)');

  // Map access: v[key] -> (select v key)
  e = e.replace(/(\w+)\[([^\]]+)\]/g, (_, base, key) => {
    const suffixed = suffix && stateVarNames.has(base) ? `${base}${suffix}` : base;
    return `(select ${suffixed} ${key.trim()})`;
  });

  // Handle 'not expr' guard — wrap: not isOn -> (not isOn)
  // Only if expr starts with 'not ' and rest is a simple identifier
  if (/^not\s+(\w+)\s*$/.test(e)) {
    const rest = e.substring(4).trim();
    const restZ3 = suffix && stateVarNames.has(rest) ? `${rest}${suffix}` : rest;
    // Restore strings
    return restoreStrings(`(not ${restZ3})`, strings);
  }

  // Add suffix to state variable references
  if (suffix) {
    e = e.replace(/\b([a-zA-Z_]\w*)\b/g, (match, id) => {
      if (stateVarNames.has(id) && !reservedWords.has(id) && !id.startsWith('__')) {
        return `${id}${suffix}`;
      }
      return match;
    });
  }

  // Handle 'in' for set membership (but not already wrapped in select)
  e = e.replace(/(\b\w+)\s+in\s+(\b\w+)/g, (match, x, set) => {
    if (reservedWords.has(set) || set.startsWith('__') || reservedWords.has(x)) return match;
    // Don't re-wrap if already inside a (select ...)
    return `(select ${set} ${x})`;
  });

  // Replace operators with placeholder tokens to avoid regex conflicts
  e = e.replace(/===/g, '__EQ__');
  e = e.replace(/==/g, '__EQ__');
  e = e.replace(/!=/g, '__NE__');
  e = e.replace(/>=/g, '__GE__');
  e = e.replace(/<=/g, '__LE__');

  // Replace && and || with and/or for SMT-LIB2
  e = e.replace(/&&/g, 'and');
  e = e.replace(/\|\|/g, 'or');

  // Convert infix to prefix
  e = convertToPrefix(e);

  // Fix length marker: len__args__xx → Z3-compatible form
  // Use declared speckl_len functions since Z3 arrays don't have built-in length
  e = e.replace(/len__([^_]\S*?)__xx/g, (_, args) => {
    // Determine sort from context — default to Int array length
    return `(speckl_len_Int ${args})`;
  });
  e = e.replace(/min__([^_]\S*?)__([^_]\S*?)__xx/g, (_, a, b) => {
    return `(ite (<= ${a} ${b}) ${a} ${b})`;
  });

  // Fix i-1 → (- i 1) in SMT-LIB2 (select indices)
  e = e.replace(/\b(\w+)-(\d+)\b/g, '(- $1 $2)');

  // Restore operators to SMT-LIB2
  e = e.replace(/__EQ__/g, '=');
  e = e.replace(/__NE__/g, 'distinct');
  e = e.replace(/__GE__/g, '>=');
  e = e.replace(/__LE__/g, '<=');

  // Wrap distinct: X distinct Y → (distinct X Y)
  // Handle both simple identifiers and parenthesized expressions
  e = e.replace(/(\b\w+|\([^()]+\))\s+distinct\s+(\b\w+|\([^()]+\))/g, '(distinct $1 $2)');

  // Fix remaining infix operators that escaped convertToPrefix
  // word = word/val: convert to (= word val)
  e = e.replace(/(\b\w+)\s*=\s*(\w+|\d+|Bool|true|false)\b/g, '(= $1 $2)');
  // (innermost expr) = val: convert to (= (expr) val)
  e = e.replace(/\(([^()]+)\)\s*=\s*(\w+|\d+|Bool|true|false)\b/g, '(= ($1) $2)');
  // word <= word: convert to (<= word word)
  e = e.replace(/(\b\w+)\s*(<=|>=)\s*(\w+|\d+|Bool|true|false)\b/g, '($2 $1 $3)');
  // (innermost expr) <= val: convert to (<= (expr) val)
  e = e.replace(/\(([^()]+)\)\s*(<=|>=)\s*(\w+|\d+|Bool|true|false)\b/g, '($2 ($1) $3)');
  // Restore strings
  e = restoreStrings(e, strings);

  return e;
}

function restoreStrings(expr: string, strings: string[]): string {
  return expr.replace(/__STR_(\d+)__/g, (_, i) => strings[parseInt(i)]);
}

/**
 * Convert infix expression to SMT-LIB2 prefix notation.
 * Handles operators: =>, and, or, =, <, >, <=, >=, +, -
 * Also wraps unary 'not' in parens so it doesn't merge with siblings.
 */
function convertToPrefix(expr: string): string {
  // Wrap bare 'not <operand>' as (not <operand>) before binary conversion.
  // This fixes the 'not A || B' → '(or not A B)' bug by producing '(or (not A) B)'.
  // Only match 'not' at the top level (not inside already-parenthesized sub-exprs).
  expr = wrapNotOperator(expr);
  expr = convertOp(expr, '=>', '=>');
  expr = convertOp(expr, 'distinct', 'distinct');
  expr = convertOp(expr, 'and', 'and');
  expr = convertOp(expr, 'or', 'or');
  expr = convertOp(expr, '=', '=');
  expr = convertOp(expr, '>', '>');
  expr = convertOp(expr, '<', '<');
  expr = convertOp(expr, '>=', '>=');
  expr = convertOp(expr, '<=', '<=');
  expr = convertOp(expr, '+', '+');
  expr = convertOp(expr, '-', '-');
  return expr;
}

/**
 * Replace implies(X, Y) with (=> X Y) using balanced-paren matching.
 * Handles nested expressions in both arguments, e.g.:
 *   implies(branch_id > 0, exists b in branches: b.branch_id == branch_id)
 *   implies(p1 != p2, p1.host_wg_key != p2.host_wg_key and p1.mesh_ip != p2.mesh_ip)
 */
function replaceImpliesCall(e: string): string {
  let result = e;
  let changed = true;
  // Loop to handle multiple implies() calls in the same string.
  while (changed) {
    changed = false;
    const idx = result.indexOf('implies');
    if (idx === -1) break;
    // Check it's a function call (followed by optional whitespace then '(')
    let j = idx + 7;
    while (j < result.length && /\s/.test(result[j])) j++;
    if (j >= result.length || result[j] !== '(') break;

    // Find the matching close paren starting from j.
    let depth = 0;
    let closeIdx = -1;
    for (let k = j; k < result.length; k++) {
      if (result[k] === '(') depth++;
      else if (result[k] === ')') {
        depth--;
        if (depth === 0) {
          closeIdx = k;
          break;
        }
      }
    }
    if (closeIdx === -1) break;

    // Extract the inner content between the outer parens.
    const inner = result.substring(j + 1, closeIdx);
    // Split on the top-level comma (depth 0 relative to inner).
    let commaIdx = -1;
    let d = 0;
    for (let k = 0; k < inner.length; k++) {
      if (inner[k] === '(') d++;
      else if (inner[k] === ')') d--;
      else if (inner[k] === ',' && d === 0) {
        commaIdx = k;
        break;
      }
    }
    if (commaIdx === -1) break;

    const arg1 = inner.substring(0, commaIdx).trim();
    const arg2 = inner.substring(commaIdx + 1).trim();
    const replacement = `(=> ${arg1} ${arg2})`;
    result = result.substring(0, idx) + replacement + result.substring(closeIdx + 1);
    changed = true;
  }
  return result;
}

/**
 * Find 'not <operand>' at the top level (depth 0) and wrap it as (not <operand>).
 * This ensures 'not A || B' becomes '(not A) || B' before convertOp('or') runs,
 * so the result is '(or (not A) B)' not '(or not A B)'.
 */
function wrapNotOperator(expr: string): string {
  // Look for 'not ' at depth 0, followed by a word (the operand).
  // The operand extends to the next top-level binary operator or end of string.
  const result: string[] = [];
  let i = 0;
  let depth = 0;
  while (i < expr.length) {
    if (expr[i] === '(') depth++;
    else if (expr[i] === ')') depth--;

    if (depth === 0 && expr.substring(i, i + 4) === 'not ' &&
        (i === 0 || /\s/.test(expr[i - 1]) || expr[i - 1] === '(')) {
      // Found 'not ' at top level — extract the operand.
      const operandStart = i + 4;
      let operandEnd = operandStart;
      let opDepth = 0;
      // The operand is a single atom (identifier, number, or parenthesized expr).
      if (expr[operandStart] === '(') {
        // Parenthesized: take the whole paren group.
        opDepth = 1;
        operandEnd = operandStart + 1;
        while (operandEnd < expr.length && opDepth > 0) {
          if (expr[operandEnd] === '(') opDepth++;
          else if (expr[operandEnd] === ')') opDepth--;
          operandEnd++;
        }
      } else {
        // Atom: read until whitespace or end.
        while (operandEnd < expr.length && !/\s/.test(expr[operandEnd])) {
          operandEnd++;
        }
      }
      const operand = expr.substring(operandStart, operandEnd).trim();
      result.push(`(not ${operand})`);
      i = operandEnd;
      continue;
    }
    result.push(expr[i]);
    i++;
  }
  return result.join('');
}

function convertOp(expr: string, op: string, smtOp: string): string {
  // Find top-level operator occurrence (outside any parens)
  let depth = 0;
  for (let i = 0; i < expr.length; i++) {
    if (expr[i] === '(') depth++;
    else if (expr[i] === ')') depth--;
    else if (depth === 0 && expr.substring(i, i + op.length) === op) {
      const beforeOk = i === 0 || /\s/.test(expr[i - 1]) || expr[i - 1] === '(';
      const afterOk = i + op.length >= expr.length || /\s/.test(expr[i + op.length]) || expr[i + op.length] === ')';
      if (beforeOk && afterOk) {
        const left = expr.substring(0, i).trim();
        const right = expr.substring(i + op.length).trim();
        return `(${smtOp} ${convertToPrefix(left)} ${convertToPrefix(right)})`;
      }
    }
  }
  // Already in prefix form
  return expr;
}

// --- Action transition predicate emission ---

function emitActionTransition(lines: string[], action: ActionNode, stateVars: StateVar[]): void {
  const funName = `${action.name}Enabled`;
  const nextName = `${action.name}Step`;

  // Collect preconditions and requires
  const guards: string[] = [];
  const assigns: { target: string; expr: string }[] = [];

  for (const s of action.statements) {
    if (s.type === 'precondition' || s.type === 'require') {
      guards.push(s.expr);
    } else if (s.type === 'assign') {
      assigns.push({ target: s.target, expr: s.expr });
    }
  }

  // Enablement predicate: all guards hold
  if (guards.length > 0) {
    lines.push(`(define-fun ${funName} () Bool`);
    lines.push('  (and');
    for (const g of guards) {
      const z3Expr = translateExpr(g, stateVars, '');
      lines.push(`    ${z3Expr}`);
    }
    lines.push('  )');
    lines.push(')');
  }

  // Step predicate: relates pre- and post-state
  if (assigns.length > 0) {
    lines.push(`(define-fun ${nextName} () Bool`);
    lines.push('  (and');
    for (const a of assigns) {
      // a.target becomes post-state, RHS reads pre-state
      // Target: if it's a simple name, post-state; if indexed, translate
      const z3RHS = translateExpr(a.expr, stateVars, '');
      if (a.target.includes('[')) {
        const z3Target = translateExpr(a.target, stateVars, "_post");
        lines.push(`    (= ${z3Target} ${z3RHS})`);
      } else {
        lines.push(`    (= ${a.target}_post ${z3RHS})`);
      }
    }
    lines.push('  )');
    lines.push(')');
  }
}

// --- Next transition relation ---

function emitNextTransition(
  lines: string[],
  speckName: string,
  nextNode: NextNode,
  actions: ActionNode[],
  stateVars: StateVar[]
): void {
  const actionNames = new Set(actions.map(a => a.name));
  const validActions = nextNode.actions.filter(a => actionNames.has(a));

  if (validActions.length === 0) return;

  lines.push(`; Next transition relation: ${validActions.join(' | ')}`);
  lines.push(`(define-fun Next () Bool`);
  lines.push('  (or');

  for (const aName of validActions) {
    const action = actions.find(a => a.name === aName);
    if (action) {
      const enabled = `${aName}Enabled`;
      const step = `${aName}Step`;

      // Check if enabled and step predicates exist
      const hasEnabled = action.statements.some(s => s.type === 'precondition' || s.type === 'require');
      const hasStep = action.statements.some(s => s.type === 'assign');

      if (hasEnabled && hasStep) {
        lines.push(`    (and (${enabled}) (${step}))`);
      } else if (hasEnabled) {
        lines.push(`    (and (${enabled})`);
        lines.push('      (and');
        for (const v of stateVars) {
          lines.push(`        (= ${v.name}_post ${v.name})`);
        }
        lines.push('      )');
        lines.push('    )');
      } else if (hasStep) {
        lines.push(`    (${step})`);
      }
    }
  }

  // Stuttering step: nothing changes
  lines.push('    ; Stuttering step');
  lines.push('    (and');
  for (const v of stateVars) {
    lines.push(`      (= ${v.name}_post ${v.name})`);
  }
  lines.push('    )');

  lines.push('  )');
  lines.push(')');
}

// --- Bounded Model Checking ---

function emitBMC(
  lines: string[],
  speckName: string,
  verify: VerifyNode,
  invariants: InvariantNode[],
  actions: ActionNode[],
  nextNode: NextNode | null,
  stateVars: StateVar[],
  options: Z3Options
): void {
  const depth = verify.depth || options.verifyDepth;
  const temporalExpr = verify.temporalExpr;
  const invariantName = verify.name;

  lines.push(`; Verification: ${temporalExpr}`);
  lines.push(`; BMC depth: ${depth}`);

  const isAlways = temporalExpr.startsWith('Always(') || temporalExpr.startsWith('always(');
  const isEventually = temporalExpr.startsWith('Eventually(') || temporalExpr.startsWith('eventually(');

  // Declare state variables at each step
  lines.push('');
  lines.push(`; Declare state copies for ${depth} steps`);
  for (const v of stateVars) {
    for (let i = 0; i <= depth; i++) {
      const sort = z3Sort(v.typeExpr);
      lines.push(`(declare-const ${v.name}_${i} ${sort})`);
    }
  }

  // Init state constraints (from spec init block)
  lines.push('');
  lines.push('; Initial state constraints');
  lines.push('(assert');
  lines.push('  (and');

  // Apply init assignments
  const stateNode = stateVars.length > 0 ? { type: 'state' as const, variables: stateVars } : null;
  // We need the init block
  const initMembers = speckName.length > 0 ? undefined : undefined;

  // Default init: use defaultInit from state vars
  for (const v of stateVars) {
    if (v.defaultInit) {
      const z3Val = translateInitValue(v.defaultInit, v.typeExpr);
      lines.push(`    (= ${v.name}_0 ${z3Val})`);
    } else {
      // Default: 0 for Nat/Int, false for Bool, "" for String
      if (v.typeExpr.type === 'primitive') {
        switch (v.typeExpr.name) {
          case 'Nat': case 'Int': lines.push(`    (>= ${v.name}_0 0)`); break;
          case 'Bool': lines.push(`    (or (= ${v.name}_0 true) (= ${v.name}_0 false))`); break;
          default: break; // unconstrained
        }
      }
    }
  }

  lines.push('  )');
  lines.push(')');

  // Transition constraints for each step
  lines.push('');
  lines.push('; Transition constraints');
  for (let i = 0; i < depth; i++) {
    const actionNames = nextNode?.actions ?? [];
    const validActions = actionNames.filter(a => actions.some(act => act.name === a));

    lines.push(`(assert ; Step ${i} → ${i + 1}`);
    lines.push('  (or');

    for (const aName of validActions) {
      const action = actions.find(a => a.name === aName);
      if (!action) continue;

      const guards: string[] = [];
      const stepAssigns: string[] = [];

      for (const s of action.statements) {
        if (s.type === 'precondition' || s.type === 'require') {
          guards.push(s.expr);
        } else if (s.type === 'assign') {
          if (s.target.includes('[')) {
            const z3LHS = translateExpr(s.target, stateVars, `_${i + 1}`);
            const z3RHS = translateExpr(s.expr, stateVars, `_${i}`);
            stepAssigns.push(`(= ${z3LHS} ${z3RHS})`);
          } else {
            const z3RHS = translateExpr(s.expr, stateVars, `_${i}`);
            stepAssigns.push(`(= ${s.target}_${i + 1} ${z3RHS})`);
          }
        }
      }

      if (guards.length > 0 || stepAssigns.length > 0) {
        lines.push(`    (and ; Action: ${aName}`);

        // Guards at step i
        for (const g of guards) {
          const z3Expr = translateExpr(g, stateVars, `_${i}`);
          lines.push(`      ${z3Expr}`);
        }

        // Step assignments
        for (const a of stepAssigns) {
          lines.push(`      ${a}`);
        }

        // Frame: unchanged vars
        const changedVars = new Set(action.statements
          .filter(s => s.type === 'assign')
          .map(s => s.target.replace(/\[.*\]/, '')));
        for (const v of stateVars) {
          if (!changedVars.has(v.name)) {
            lines.push(`      (= ${v.name}_${i + 1} ${v.name}_${i})`);
          }
        }

        lines.push('    )');
      }
    }

    // Stuttering
    lines.push('    ; Stuttering');
    lines.push('    (and');
    for (const v of stateVars) {
      lines.push(`      (= ${v.name}_${i + 1} ${v.name}_${i})`);
    }
    lines.push('    )');

    lines.push('  )');
    lines.push(')');
  }

  // Property to check: find invariant and assert its negation at some step
  lines.push('');
  lines.push('; Property assertion: not(invariant at some step)');

  if (isAlways && invariantName) {
    const inv = invariants.find(i => i.name === invariantName);
    if (inv) {
      // Always p = for all steps up to depth, p holds
      // To check: assert there exists step where p fails
      // If UNSAT: p always holds within bound
      // If SAT: counterexample found

      lines.push('(assert');
      lines.push('  (or');
      for (let i = 0; i <= depth; i++) {
        lines.push(`    (not (${inv.name}_${i}))`);
      }
      lines.push('  )');
      lines.push(')');

      // Emit invariant instances at each step
      for (let i = 0; i <= depth; i++) {
        emitInvariantInstance(lines, inv, stateVars, i);
      }

      lines.push('');
      lines.push(`(echo "Checking: Always(${invariantName}) for ${depth} steps")`);
      lines.push('(check-sat)');
      lines.push('(get-model)');

    } else {
      lines.push(`; Warning: invariant "${invariantName}" not found in spec`);
      lines.push('(check-sat)');
      lines.push('(get-model)');
    }
  } else if (isEventually && invariantName) {
    // Eventually p = exists step up to depth where p holds
    // This is approximated for BMC
    lines.push('(assert');
    lines.push('  (and');
    for (let i = 0; i <= depth; i++) {
      lines.push(`    (not (${invariantName}_${i}))`);
    }
    lines.push('  )');
    lines.push(')');

    for (let i = 0; i <= depth; i++) {
      const inv = invariants.find(inv => inv.name === invariantName);
      if (inv) {
        emitInvariantInstance(lines, inv, stateVars, i);
      }
    }

    lines.push(`(echo "Checking: Eventually(${invariantName})")`);
    lines.push('(check-sat)');
    lines.push('(get-model)');
  } else {
    lines.push(`; Verification property: ${temporalExpr}`);
    lines.push('(check-sat)');
    lines.push('(get-model)');
  }
}

function extractInvariantName(temporalExpr: string): string | null {
  const match = temporalExpr.match(/(?:Always|always|Eventually|eventually)\s*\(\s*(\w+)\s*\)/);
  return match ? match[1] : null;
}

function emitInvariantInstance(lines: string[], inv: InvariantNode, stateVars: StateVar[], step: number): void {
  lines.push(`(define-fun ${inv.name}_${step} () Bool`);
  lines.push('  (and');

  for (const stmt of inv.statements) {
    if (stmt.type === 'require') {
      const z3Expr = translateExpr(stmt.expr, stateVars, `_${step}`);
      lines.push(`    ${z3Expr}`);
    } else if (stmt.type === 'forall') {
      const domainSort = inferDomainSort(stmt.domain, stateVars);
      const z3Expr = translateExpr(stmt.expr, stateVars, `_${step}`);
      lines.push(`    (forall ((${stmt.var} ${domainSort})) ${z3Expr})`);
    } else if (stmt.type === 'forall_complex') {
      const bindings = stmt.vars.map((v, i) => {
        const sort = inferDomainSort(stmt.domains[i], stateVars);
        return `(${v} ${sort})`;
      }).join(' ');
      const z3Expr = translateExpr(stmt.expr, stateVars, `_${step}`);
      lines.push(`    (forall (${bindings}) ${z3Expr})`);
    }
  }

  lines.push('  )');
  lines.push(')');
}

function translateInitValue(val: string, typeExpr: TypeExpr): string {
  if (val === 'false') return 'false';
  if (val === 'true') return 'true';
  if (val === 'emptySet') {
    const elemSort = z3Sort(typeExpr.elementType!);
    return `((as const (Array ${elemSort} Bool)) false)`;
  }
  if (val === 'emptyMap') {
    const keySort = z3Sort(typeExpr.keyType!);
    const valSort = z3Sort(typeExpr.valueType!);
    // Use const array for maps too — all values default to some baseline
    return `((as const (Array ${keySort} ${valSort})) 0)`;
  }
  if (val === 'emptyList') {
    const elemSort = z3Sort(typeExpr.elementType!);
    return `((as const (Array Int ${elemSort})) 0)`;
  }
  // Numeric literal
  if (/^\d+$/.test(val)) return val;
  // Otherwise, treat as identifier
  return val;
}

// --- Invariant extraction from constraint nodes ---

/**
 * Convert parsed ConstraintNode entries into InvariantNode format
 * so they can be emitted as Z3 define-fun assertions.
 *
 * Constraint nodes from the parser:
 *   { type: 'constraint', name: 'ReadConsistency', expr: 'forall r in [0..4]: ...' }
 *
 * We convert them to:
 *   { type: 'invariant', name: 'ReadConsistency', statements: [
 *     { type: 'require', expr: 'forall r in ...' } | { type: 'forall', ... }
 *   ]}
 */
function extractInvariantsFromConstraints(constraints: ConstraintNode[]): InvariantNode[] {
  const invariants: InvariantNode[] = [];
  
  for (const c of constraints) {
    const name = c.name || `constraint_${invariants.length}`;
    const expr = c.expr.trim();
    
    if (!expr) continue;
    
    // Detect English-language constraints that can't be translated to SMT-LIB2.
    // These are constraints with natural language like "has unique entries by (...)"
    // or other non-formal syntax. Skip them with a warning comment.
    if (isEnglishLanguageConstraint(expr)) {
      console.warn(`Warning: constraint "${name}" appears to be an English-language constraint and cannot be translated to SMT-LIB2. Skipping: "${expr.substring(0, 80)}..."`);
      // Emit a warning invariant (empty body with a comment)
      invariants.push({
        type: 'invariant',
        name,
        statements: [{ type: 'require', expr: '; WARNING: English-language constraint skipped: ' + expr.substring(0, 100) }],
      });
      continue;
    }
    
    // Try to parse forall statements in the expression
    const statements = parseInvariantBody(expr);
    invariants.push({ type: 'invariant', name, statements });
  }
  
  return invariants;
}

/**
 * Detect English-language constraints that cannot be translated to SMT-LIB2.
 * These typically contain natural language phrases like:
 *   - "has unique entries by (...)"
 *   - "must be unique"
 *   - "should always"
 *   - "is required to"
 *   - no formal operators (no =, <, >, <=, >=, &&, ||, implies, forall, exists)
 */
function isEnglishLanguageConstraint(expr: string): boolean {
  // Check for common English-language patterns
  const englishPatterns = [
    /\bhas\s+unique\s+entries\b/i,
    /\bmust\s+be\s+unique\b/i,
    /\bshould\s+always\b/i,
    /\bis\s+required\s+to\b/i,
    /\bhas\s+at\s+least\b/i,
    /\bhas\s+at\s+most\b/i,
    /\bhas\s+exactly\b/i,
    /\bmust\s+not\s+exceed\b/i,
    /\bmay\s+not\s+be\s+(empty|nil|null)\b/i,
  ];
  for (const p of englishPatterns) {
    if (p.test(expr)) return true;
  }
  
  // If the expression has no formal operators at all, it's likely English.
  // Formal operators: =, ==, !=, <, >, <=, >=, &&, ||, implies, forall, exists,
  //                   in, not, len(, length(, +, -, *, /
  const hasFormalOp = /[=<>!&|]|\bimplies\b|\bforall\b|\bexists\b|\bin\b|\bnot\b|\blen\s*\(|\blength\s*\(|[+\-*/]/.test(expr);
  if (!hasFormalOp) return true;
  
  return false;
}

function parseInvariants(speck: SpeckNode): InvariantNode[] {
  // Legacy stub — returns empty, new code uses extractInvariantsFromConstraints
  return [];
}

/**
 * Parse invariants from the raw .speckdl source content.
 * This function is called with the raw file content and the speck name
 * to find and parse invariant blocks that the main parser doesn't handle yet.
 */
export function parseInvariantsFromSource(source: string, speckName: string): InvariantNode[] {
  const invariants: InvariantNode[] = [];

  // Find the speck block for this name
  const speckRegex = new RegExp(`speck\\s+${escapeRegex(speckName)}\\s*\\{`);
  const speckMatch = source.match(speckRegex);
  if (!speckMatch) return invariants;

  // Extract the speck body
  const startIdx = speckMatch.index! + speckMatch[0].length;
  let braceCount = 1;
  let endIdx = startIdx;
  for (let i = startIdx; i < source.length; i++) {
    if (source[i] === '{') braceCount++;
    if (source[i] === '}') {
      braceCount--;
      if (braceCount === 0) {
        endIdx = i;
        break;
      }
    }
  }

  const body = source.substring(startIdx, endIdx);

  // Find invariant blocks using brace counting (handles nested { })
  const invPattern = /invariant\s+(\w+)\s*\{/g;
  let match;
  while ((match = invPattern.exec(body)) !== null) {
    const name = match[1];
    // Find matching close brace
    const blockStart = match.index + match[0].length;
    let braceDepth = 1;
    let blockEnd = blockStart;
    for (let i = blockStart; i < body.length; i++) {
      if (body[i] === '{') braceDepth++;
      if (body[i] === '}') {
        braceDepth--;
        if (braceDepth === 0) {
          blockEnd = i;
          break;
        }
      }
    }
    const content = body.substring(blockStart, blockEnd);

    const statements = parseInvariantBody(content);
    invariants.push({ type: 'invariant', name, statements });
  }

  return invariants;
}

function parseInvariantBody(content: string): InvariantStatement[] {
  const statements: InvariantStatement[] = [];
  const lines = content.split('\n');

  let i = 0;
  while (i < lines.length) {
    const rawLine = lines[i];
    const line = rawLine.trim();
    if (!line || line.startsWith('//')) { i++; continue; }

    // forall var in domain: (body on next line(s))
    // domain can be: [0..4], someVar.keys, someVar.values, etc.
    const forallHeaderMatch = line.match(/^forall\s+(\w+)\s+in\s+(\[?[\w.\-\d]+\]?):\s*$/);
    if (forallHeaderMatch) {
      const bodyLines: string[] = [];
      i++;
      while (i < lines.length) {
        const nextLine = lines[i];
        if (!nextLine.trim() || nextLine.trim().startsWith('//')) { i++; continue; }
        // Don't break on nested forall — collect it as part of the body.
        // Only break on non-indented lines that aren't forall/implies/etc.
        if (!/^\s+/.test(nextLine) && !/^forall\s+/.test(nextLine.trim())) break;
        bodyLines.push(nextLine.trim());
        i++;
      }
      if (bodyLines.length > 0) {
        statements.push({
          type: 'forall',
          var: forallHeaderMatch[1],
          domain: forallHeaderMatch[2],
          expr: bodyLines.join(' '),
        });
      }
      continue;
    }

    // forall var in domain: expr (single line)
    // domain can be: [0..4], accounts.values, log.indices, transfers.keys, etc.
    const forallMatch = line.match(/^forall\s+(\w+)\s+in\s+(\[?[\w.\d\-]+\]?):\s*(.+)$/);
    if (forallMatch) {
      statements.push({
        type: 'forall',
        var: forallMatch[1],
        domain: forallMatch[2],
        expr: forallMatch[3].trim(),
      });
      i++; continue;
    }

    // forall var1, var2 in domain1, domain2: expr (complex)
    // domains may include bracket notation and dots
    const complexForallMatch = line.match(/^forall\s+([\w,\s]+)\s+in\s+([\[\]\w\s.,\-]+):\s*(.+)$/);
    if (complexForallMatch) {
      const vars = complexForallMatch[1].split(',').map((s: string) => s.trim()).filter(Boolean);
      const domains = complexForallMatch[2].split(',').map((s: string) => s.trim()).filter(Boolean);
      if (vars.length > 1 || domains.length > 1) {
        statements.push({
          type: 'forall_complex',
          vars, domains,
          expr: complexForallMatch[3].trim(),
        });
        i++; continue;
      }
      statements.push({
        type: 'forall',
        var: vars[0], domain: domains[0],
        expr: complexForallMatch[3].trim(),
      });
      i++; continue;
    }

    statements.push({ type: 'require', expr: line });
    i++;
  }

  return statements;
}

/**
 * Parse next: transition relation from raw source
 */
export function parseNextFromSource(source: string, speckName: string): NextNode | null {
  const speckRegex = new RegExp(`speck\\s+${escapeRegex(speckName)}\\s*\\{`);
  const speckMatch = source.match(speckRegex);
  if (!speckMatch) return null;

  const startIdx = speckMatch.index! + speckMatch[0].length;
  let braceCount = 1;
  let endIdx = startIdx;
  for (let i = startIdx; i < source.length; i++) {
    if (source[i] === '{') braceCount++;
    if (source[i] === '}') {
      braceCount--;
      if (braceCount === 0) {
        endIdx = i;
        break;
      }
    }
  }

  const body = source.substring(startIdx, endIdx);

  // next: Action1 | Action2 | ... (can span multiple lines)
  const nextMatch = body.match(/next:\s*(.+)/s);
  if (!nextMatch) return null;

  // The captured group contains everything from 'next' to end of speck body
  // We need to extract just the action names before the next block starts
  const rest = nextMatch[1];
  // Stop at verify: block, or end of speck body
  const endMarker = rest.match(/\n\s*(?:verify:|speck\s)/);
  const nextContent = endMarker ? rest.substring(0, endMarker.index!) : rest;

  const actions = nextContent
    .replace(/\n/g, ' ')  // collapse newlines
    .split('|')
    .map(s => s.trim())
    .filter(Boolean);

  return { type: 'next', actions };
}

function parseNext(speck: SpeckNode): NextNode | null {
  // Parsed from source, not AST
  return null;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
