// src/generators/__tests__/protobuf.test.ts
//
// Tests for the protobuf (.proto3) backend generator. The generator must:
//   - Emit valid proto3 syntax with syntax = "proto3";
//   - Map SpeckDL types to proto3 types (String→string, Nat→uint64, Bool→bool, etc.)
//   - Emit interface records as proto3 messages
//   - Emit interface enums as proto3 enums (with UNSPECIFIED = 0 + prefixed variants)
//   - Emit events as messages (with optional event_suffix)
//   - Emit state blocks as StateSnapshot messages
//   - Emit transition blocks with inline oneof payload
//   - Emit service blocks with rpc methods
//   - Use deterministic alphabetical field numbering (byte-stable)
//   - Support Map<K,V> → map<K,V> proto syntax
//   - Support List<T> → repeated T proto syntax
//   - Support Set<T> → repeated T proto syntax
//   - Populate option go_package from speck metadata
//   - Populate package from proto_package directive
//   - Parse `service { rpc X(...) returns (...); }` syntax cleanly

import { describe, it, expect } from 'vitest';
import { join } from 'path';
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import { parseSpeckContent, parseSpeckFile } from '../../parser.js';
import { generateProtobuf } from '../protobuf.js';

// ─── Helpers ──────────────────────────────────────────────

function compileProto(src: string, speckName?: string): string {
  const filePath = '/tmp/speckl-protobuf-test.speckdl';
  writeFileSync(filePath, src);
  const ast = parseSpeckFile(filePath);
  const tmp = mkdtempSync(join(tmpdir(), 'speckl-proto-'));
  try {
    generateProtobuf(ast, tmp);
    const name = speckName || ast.specks[0].name;
    const protoPath = join(tmp, snakeCaseFile(name) + '.proto');
    if (!existsSync(protoPath)) {
      // List files to help debug
      const { readdirSync } = require('fs');
      throw new Error(`Expected proto file not found: ${protoPath}. Files in tmp: ${readdirSync(tmp).join(', ')}`);
    }
    return readFileSync(protoPath, 'utf-8');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

// The generator uses snakeCase for filenames
function snakeCaseFile(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function parseInline(src: string) {
  return parseSpeckContent(src);
}

// ─── Tests ─────────────────────────────────────────────────

describe('Protobuf backend: basic structure', () => {
  it('emits valid proto3 syntax header', () => {
    const proto = compileProto(`
speck ToggleSwitch {
  state {
    isOn: Bool
  }
}
`);
    expect(proto).toContain('syntax = "proto3";');
    expect(proto).toContain('// Auto-generated by speckl-compile');
    expect(proto).toContain('DO NOT EDIT MANUALLY');
  });

  it('emits package from proto_package directive', () => {
    const proto = compileProto(`
speck MySpec {
  proto_package: "com.example.v1"
  state {
    count: Nat
  }
}
`);
    expect(proto).toContain('package com.example.v1;');
  });

  it('emits default package when no proto_package specified', () => {
    const proto = compileProto(`
speck SimpleSpec {
  state {
    value: Nat
  }
}
`);
    expect(proto).toContain('package speckl.simple_spec.v1;');
  });

  it('emits option go_package from go_package directive', () => {
    const proto = compileProto(`
speck MySpec {
  proto_package: "com.example.v1"
  go_package: "github.com/foo/bar/proto/v1;barv1"
  state {
    count: Nat
  }
}
`);
    expect(proto).toContain('option go_package = "github.com/foo/bar/proto/v1;barv1";');
  });

  it('emits default go_package when not specified', () => {
    const proto = compileProto(`
speck SimpleSpec {
  state {
    value: Nat
  }
}
`);
    expect(proto).toContain('option go_package =');
    // Default go_package follows the pattern github.com/sscoble/<name>/proto/<name>/v1;<name>v1
    expect(proto).toContain('github.com/sscoble/simple_spec/proto/simple_spec/v1');
  });
});

describe('Protobuf backend: type mapping', () => {
  it('maps SpeckDL primitives to proto3 types', () => {
    const proto = compileProto(`
speck TypeTest {
  interface Fields {
    a: String,
    b: Nat,
    c: Int,
    d: Bool,
    e: Bytes,
    f: Real
  }
}
`);
    expect(proto).toContain('string a =');
    expect(proto).toContain('uint64 b =');
    expect(proto).toContain('int64 c =');
    expect(proto).toContain('bool d =');
    expect(proto).toContain('bytes e =');
    expect(proto).toContain('double f =');
  });

  it('maps StringList to repeated string', () => {
    const proto = compileProto(`
speck ListTest {
  interface Record {
    names: StringList,
    ids: NatList,
    flags: BoolList,
    blobs: BytesList
  }
}
`);
    expect(proto).toContain('repeated string names =');
    expect(proto).toContain('repeated uint64 ids =');
    expect(proto).toContain('repeated bool flags =');
    expect(proto).toContain('repeated bytes blobs =');
  });

  it('maps List<T> to repeated T', () => {
    const proto = compileProto(`
speck GenericListTest {
  interface Record {
    items: List<String>,
    counts: List<Nat>
  }
}
`);
    expect(proto).toContain('repeated string items =');
    expect(proto).toContain('repeated uint64 counts =');
  });

  it('maps Set<T> to repeated T', () => {
    const proto = compileProto(`
speck SetTest {
  interface Record {
    tags: Set<String>
  }
}
`);
    expect(proto).toContain('repeated string tags =');
  });

  it('maps Map<K,V> to map<K,V>', () => {
    const proto = compileProto(`
speck MapTest {
  interface Record {
    entries: Map<String, Nat>,
    lookup: Map<Nat, Bool>
  }
}
`);
    expect(proto).toContain('map<string, uint64> entries =');
    expect(proto).toContain('map<uint64, bool> lookup =');
  });

  it('imports google/protobuf/timestamp.proto when Date type is used', () => {
    const proto = compileProto(`
speck DateTest {
  interface Record {
    created: Date
  }
}
`);
    expect(proto).toContain('import "google/protobuf/timestamp.proto";');
    expect(proto).toContain('google.protobuf.Timestamp created =');
  });
});

describe('Protobuf backend: enums', () => {
  it('emits interface enums as proto3 enums with UNSPECIFIED = 0', () => {
    const proto = compileProto(`
speck EnumTest {
  interface Status {
    Active,
    Inactive,
    Pending
  }
}
`);
    expect(proto).toContain('enum Status {');
    expect(proto).toContain('STATUS_UNSPECIFIED = 0;');
    expect(proto).toContain('STATUS_ACTIVE = 1;');
    expect(proto).toContain('STATUS_INACTIVE = 2;');
    expect(proto).toContain('STATUS_PENDING = 3;');
  });

  it('prefixes enum variants to avoid cross-enum collisions', () => {
    const proto = compileProto(`
speck MultiEnumTest {
  interface Role {
    Admin,
    User,
    Pending
  }
  interface OrderStatus {
    Created,
    Shipped,
    Pending
  }
}
`);
    // Both enums have "Pending" but with different prefixes
    expect(proto).toContain('ROLE_PENDING');
    expect(proto).toContain('ORDER_STATUS_PENDING');
    // Verify they have different values
    expect(proto).toContain('ROLE_PENDING = 3;');
    expect(proto).toContain('ORDER_STATUS_PENDING = 3;');
  });
});

describe('Protobuf backend: messages from interface records', () => {
  it('emits interface records as proto3 messages', () => {
    const proto = compileProto(`
speck RecordTest {
  interface Person {
    name: String,
    age: Nat
  }
}
`);
    expect(proto).toContain('message Person {');
    expect(proto).toContain('string name =');
    expect(proto).toContain('uint64 age =');
  });

  it('uses deterministic alphabetical field numbering', () => {
    const proto = compileProto(`
speck FieldOrderTest {
  interface Record {
    zebra: String,
    apple: Nat,
    mango: Bool
  }
}
`);
    // Fields should be numbered alphabetically: apple=1, mango=2, zebra=3
    const lines = proto.split('\n');
    const appleLine = lines.find(l => l.includes('apple ='));
    const mangoLine = lines.find(l => l.includes('mango ='));
    const zebraLine = lines.find(l => l.includes('zebra ='));
    expect(appleLine).toContain('= 1;');
    expect(mangoLine).toContain('= 2;');
    expect(zebraLine).toContain('= 3;');
  });
});

describe('Protobuf backend: events', () => {
  it('emits events as proto3 messages', () => {
    const proto = compileProto(`
speck EventTest {
  event Created {
    name: String,
    value: Nat
  }
}
`);
    expect(proto).toContain('message Created {');
    expect(proto).toContain('string name =');
    expect(proto).toContain('uint64 value =');
  });

  it('appends event_suffix to event message names', () => {
    const proto = compileProto(`
speck SuffixTest {
  event_suffix: "Payload"
  event CreateGroup {
    name: String
  }
}
`);
    expect(proto).toContain('message CreateGroupPayload {');
    expect(proto).not.toMatch(/^message CreateGroup \{/m);
  });

  it('handles empty events', () => {
    const proto = compileProto(`
speck EmptyEventTest {
  event Started {
  }
}
`);
    expect(proto).toContain('message Started {');
    expect(proto).toContain('// empty event');
  });
});

describe('Protobuf backend: state snapshot', () => {
  it('emits state as a message with snapshot fields', () => {
    const proto = compileProto(`
speck StateTest {
  state {
    count: Nat,
    name: String,
    active: Bool
  }
}
`);
    expect(proto).toContain('message StateTestState {');
    expect(proto).toContain('uint64 count =');
    expect(proto).toContain('string name =');
    expect(proto).toContain('bool active =');
  });

  it('honors state as <Name> override', () => {
    const proto = compileProto(`
speck OverrideTest {
  state as StateSnapshot {
    count: Nat
  }
}
`);
    expect(proto).toContain('message StateSnapshot {');
    expect(proto).not.toContain('message OverrideTestState {');
  });
});

describe('Protobuf backend: transitions with oneof payload', () => {
  it('emits transition message with oneof payload block', () => {
    const proto = compileProto(`
speck TransitionTest {
  event Create {
    name: String
  }
  event Delete {
    id: Nat
  }
  oneof TransitionPayload {
    create: Create,
    delete: Delete
  }
  interface TransitionType {
    Create,
    Delete
  }
  transition Transition {
    type: TransitionType,
    payload: TransitionPayload,
    hlc: Bytes
  }
}
`);
    expect(proto).toContain('message Transition {');
    expect(proto).toContain('TransitionType type = 1;');
    expect(proto).toContain('oneof payload {');
    expect(proto).toContain('Create create = 10;');
    expect(proto).toContain('Delete delete = 11;');
    expect(proto).toContain('bytes hlc =');
  });

  it('offsets field numbers when type discriminator is present', () => {
    const proto = compileProto(`
speck OffsetTest {
  event Create {
    name: String
  }
  event Delete {
    id: Nat
  }
  oneof TransitionPayload {
    create: Create,
    delete: Delete
  }
  interface TransitionType {
    Create,
    Delete
  }
  transition Transition {
    type: TransitionType,
    payload: TransitionPayload,
    branch_id: Nat,
    hlc: Bytes
  }
}
`);
    // type = 1 (discriminator), then alphabetical fields offset by 1:
    // branch_id = 2 (alphabetically first, 1+1), hlc = 3 (2+1)
    expect(proto).toContain('TransitionType type = 1;');
    expect(proto).toContain('uint64 branch_id = 2;');
    expect(proto).toContain('bytes hlc = 3;');
  });

  it('emits transition without type discriminator when absent', () => {
    const proto = compileProto(`
speck NoDiscriminatorTest {
  event Create {
    name: String
  }
  oneof Payload {
    create: Create
  }
  transition Transition {
    payload: Payload,
    hlc: Bytes
  }
}
`);
    expect(proto).toContain('message Transition {');
    // No type discriminator → hlc starts at field 1 (alphabetically)
    expect(proto).toContain('bytes hlc = 1;');
    // oneof still at 10+
    expect(proto).toContain('oneof payload {');
    expect(proto).toContain('Create create = 10;');
  });
});

describe('Protobuf backend: service blocks', () => {
  it('parses service { rpc X(...) returns (...); } syntax cleanly', () => {
    const ast = parseInline(`
speck ServiceTest {
  service MyService {
    rpc GetItem(GetItemRequest) returns (GetItemResponse);
    rpc ListItems(ListItemsRequest) returns (ListItemsResponse);
  }
}
`);
    const service = ast.specks[0].members.find(m => m.type === 'service') as any;
    expect(service).toBeDefined();
    expect(service.name).toBe('MyService');
    expect(service.rpcs).toHaveLength(2);
    expect(service.rpcs[0].name).toBe('GetItem');
    expect(service.rpcs[0].requestType).toBe('GetItemRequest');
    expect(service.rpcs[0].responseType).toBe('GetItemResponse');
    expect(service.rpcs[1].name).toBe('ListItems');
    expect(service.rpcs[1].requestType).toBe('ListItemsRequest');
    expect(service.rpcs[1].responseType).toBe('ListItemsResponse');
  });

  it('emits service block with rpc methods in proto output', () => {
    const proto = compileProto(`
speck ServiceProtoTest {
  service HostService {
    rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);
    rpc SubmitTransition(SubmitTransitionRequest) returns (SubmitTransitionResponse);
  }
}
`);
    expect(proto).toContain('service HostService {');
    expect(proto).toContain('rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);');
    expect(proto).toContain('rpc SubmitTransition(SubmitTransitionRequest) returns (SubmitTransitionResponse);');
  });

  it('parses streaming rpc methods', () => {
    const ast = parseInline(`
speck StreamTest {
  service StreamService {
    rpc Subscribe(SubscribeRequest) returns (stream TransitionEvent);
  }
}
`);
    const service = ast.specks[0].members.find(m => m.type === 'service') as any;
    expect(service).toBeDefined();
    expect(service.rpcs).toHaveLength(1);
    expect(service.rpcs[0].name).toBe('Subscribe');
    expect(service.rpcs[0].serverStreaming).toBe(true);
    expect(service.rpcs[0].responseType).toBe('TransitionEvent');
  });

  it('emits streaming rpc methods with stream keyword', () => {
    const proto = compileProto(`
speck StreamProtoTest {
  service StreamService {
    rpc Subscribe(SubscribeRequest) returns (stream TransitionEvent);
  }
}
`);
    expect(proto).toContain('rpc Subscribe(SubscribeRequest) returns (stream TransitionEvent);');
  });

  it('converts snake_case rpc names to PascalCase in proto output', () => {
    const proto = compileProto(`
speck PascalRpcTest {
  service MyService {
    rpc get_group(GetGroupRequest) returns (GetGroupResponse);
    rpc submit_transition(SubmitTransitionRequest) returns (SubmitTransitionResponse);
  }
}
`);
    expect(proto).toContain('rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);');
    expect(proto).toContain('rpc SubmitTransition(SubmitTransitionRequest) returns (SubmitTransitionResponse);');
  });

  it('throws on unrecognized lines in service blocks', () => {
    expect(() => parseInline(`
speck ErrorTest {
  service BadService {
    rc_typo(RequestType) returns (ResponseType);
  }
}
`)).toThrow(/unrecognized line/);
  });
});

describe('Protobuf backend: determinism (byte-stable)', () => {
  it('produces identical output on recompile', () => {
    const src = `
speck DeterminismTest {
  proto_package: "test.v1"
  go_package: "github.com/test/det/v1;detv1"
  interface Status {
    Active,
    Inactive
  }
  interface Record {
    name: String,
    age: Nat,
    tags: List<String>,
    meta: Map<String, Bool>
  }
  event Created {
    record_id: Nat,
    timestamp: String
  }
  state {
    records: Map<Nat, Record>,
    status: Status
  }
  service ApiService {
    rpc GetRecord(GetRecordRequest) returns (GetRecordResponse);
  }
  interface GetRecordRequest {
    id: Nat
  }
  interface GetRecordResponse {
    record: Record
  }
}
`;
    const proto1 = compileProto(src);
    const proto2 = compileProto(src);
    expect(proto1).toBe(proto2);
  });
});

describe('Protobuf backend: ToggleSwitch example', () => {
  it('compiles ToggleSwitch.speck to valid .proto', () => {
    const ast = parseSpeckFile(join('/home/sscoble/speckl', 'examples', 'ToggleSwitch.speck'));
    const tmp = mkdtempSync(join(tmpdir(), 'speckl-proto-toggle-'));
    try {
      generateProtobuf(ast, tmp);
      const protoPath = join(tmp, 'toggle_switch.proto');
      expect(existsSync(protoPath)).toBe(true);
      const proto = readFileSync(protoPath, 'utf-8');

      expect(proto).toContain('syntax = "proto3";');
      expect(proto).toContain('package speckl.toggle_switch.v1;');
      expect(proto).toContain('message ToggleSwitchState {');
      expect(proto).toContain('bool is_on = 1;');
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});

describe('Protobuf backend: federated-meetup integration', () => {
  it('compiles FederatedMeetup.speckdl with all transition payloads', () => {
    const ast = parseSpeckFile(
      join('/home/sscoble/projects/federated-meetup', 'specs', 'FederatedMeetup.speckdl')
    );
    const tmp = mkdtempSync(join(tmpdir(), 'speckl-proto-fm-'));
    try {
      generateProtobuf(ast, tmp);
      const protoPath = join(tmp, 'federated_meetup.proto');
      expect(existsSync(protoPath)).toBe(true);
      const proto = readFileSync(protoPath, 'utf-8');

      // Package and go_package
      expect(proto).toContain('package federated_meetup.v1;');
      expect(proto).toContain('option go_package = "github.com/sscoble/federated-meetup/proto/federated_meetup/v1;federatedmeetupv1";');

      // Enums
      expect(proto).toContain('enum CustodyTier {');
      expect(proto).toContain('CUSTODY_TIER_UNSPECIFIED = 0;');
      expect(proto).toContain('CUSTODY_TIER_COLD_HARDWARE = 1;');
      expect(proto).toContain('enum TransitionType {');
      expect(proto).toContain('TRANSITION_TYPE_CREATE_GROUP = 1;');

      // Key messages
      expect(proto).toContain('message PublicKey {');
      expect(proto).toContain('message Signature {');
      expect(proto).toContain('message StateRoot {');
      expect(proto).toContain('message StateSnapshot {');

      // All transition payload messages (event_suffix: "Payload")
      const payloadMessages = [
        'CreateGroupPayload',
        'AddStewardPayload',
        'RemoveStewardPayload',
        'ChangeThresholdPayload',
        'AddMemberPayload',
        'RemoveMemberPayload',
        'CreateEventPayload',
        'UpdateEventPayload',
        'CancelEventPayload',
        'RsvpPayload',
        'CancelRsvpPayload',
        'AttestPayload',
        'ForkPayload',
        'MigratePayload',
        'IssueHostCertPayload',
        'AddHostPeerPayload',
        'RemoveHostPeerPayload',
        'RevokeHostCertPayload',
        'DeclareStewardCustodyPayload',
        'SlashStewardPayload',
        'NameBindPayload',
        'BranchCreatePayload',
      ];
      for (const msg of payloadMessages) {
        expect(proto).toContain(`message ${msg} {`);
      }

      // Transition message with oneof payload
      expect(proto).toContain('message Transition {');
      expect(proto).toContain('TransitionType type = 1;');
      expect(proto).toContain('oneof payload {');
      expect(proto).toContain('CreateGroupPayload create_group = 10;');

      // Service
      expect(proto).toContain('service HostService {');
      expect(proto).toContain('rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);');
      expect(proto).toContain('rpc SubmitTransition(SubmitTransitionRequest) returns (SubmitTransitionResponse);');

      // Request/response messages
      expect(proto).toContain('message GetGroupRequest {');
      expect(proto).toContain('message GetGroupResponse {');
      expect(proto).toContain('message SubmitTransitionRequest {');
      expect(proto).toContain('message SubmitTransitionResponse {');
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('produces byte-stable output for FederatedMeetup.speckdl', () => {
    const src = readFileSync(
      join('/home/sscoble/projects/federated-meetup', 'specs', 'FederatedMeetup.speckdl'),
      'utf-8'
    );
    const proto1 = compileProto(src, 'FederatedMeetup');
    const proto2 = compileProto(src, 'FederatedMeetup');
    expect(proto1).toBe(proto2);
  });
});

describe('Protobuf backend: field name snake_case conversion', () => {
  it('converts camelCase field names to snake_case', () => {
    const proto = compileProto(`
speck SnakeCaseTest {
  interface Record {
    branchId: Nat,
    groupName: String,
    isActive: Bool
  }
}
`);
    expect(proto).toContain('uint64 branch_id =');
    expect(proto).toContain('string group_name =');
    expect(proto).toContain('bool is_active =');
  });

  it('converts camelCase event field names to snake_case', () => {
    const proto = compileProto(`
speck EventSnakeTest {
  event CreateGroup {
    canonicalName: String,
    displayName: String,
    initialMeshPeers: List<String>
  }
}
`);
    expect(proto).toContain('string canonical_name =');
    expect(proto).toContain('string display_name =');
    expect(proto).toContain('repeated string initial_mesh_peers =');
  });
});